### ISSUE TITLE
Build crash at 1%

### ISSUE THREAD

**Issue by jiayewilliamwang** [polybar/polybar#1888]
## Build Process
Clone from AUR and run makepkg. I think I followed the instruction pretty close... download all the dependencies, include optional ones. I am not using Ananconda, just python. Also googled around build() error, and still can't figure out...
## Build Log
```
==> Making package: polybar 3.4.0-4 (Mon Sep 30 19:02:04 2019)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found polybar-3.4.0.tar
==> Validating source files with sha256sums...
    polybar-3.4.0.tar ... Passed
==> Extracting sources...
  -> Extracting polybar-3.4.0.tar with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- Trying to enable ccache
-- Using compiler cache /usr/bin/ccache
-- Could not detect version with git, falling back to built-in version information.
-- No build type specified; using Release
-- Using supported compiler GNU-9.1.0
--  Build:
--    Version: 3.4.0
--    Type: Release
--    CXX: /usr/bin/c++ -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
--    LD: /usr/bin/ld -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
--  Install Paths:
--    PREFIX:  /usr
--    BINDIR:  /usr/bin
--    DATADIR: /usr/share
--    DOCDIR:  /usr/share/doc/polybar
--    MANDIR:  /usr/share/man
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
-- [X]   documentation
--  Module support:
-- [X]   alsa (1.1.9)
-- [X]   curl (7.66.0)
-- [X]   i3
-- [X]   mpd (2.16)
-- [X]   network (libnl) (3.5.0)
-- [X]   pulseaudio (13.0-dirty)
-- [X]   xkeyboard (1.13.1)
--  X extensions:
-- [X]   xcb-randr (1.13.1)
-- [X]   xcb-randr (monitor support) (1.13.1)
-- [X]   xcb-composite (1.13.1)
-- [X]   xcb-xkb (1.13.1)
-- [X]   xcb-xrm (1.3)
-- [X]   xcb-cursor (0.1.3)
--  Log options:
-- [X]   Trace logging
-- XCB[XCB]: Found component XCB
-- XCB[ICCCM]: Found component ICCCM
-- XCB[EWMH]: Found component EWMH
-- XCB[UTIL]: Found component UTIL
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so  
-- Searching for xcbgen with python2
-- Searching for xcbgen with python2.7
-- Searching for xcbgen with python3
-- Found xcbgen in /usr/lib/python3.7/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so  
-- XCB[COMPOSITE]: Found component COMPOSITE
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so;/usr/lib/libxcb-composite.so  
-- XCB[XKB]: Found component XKB
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so;/usr/lib/libxcb-composite.so;/usr/lib/libxcb-xkb.so  
-- xpp: including xcb proto composite.xml
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Configuring done
-- Generating done
-- Build files have been written to: /home/will/Downloads/polybar/src/polybar/build
[  1%] sphinx-build html: see doc/builder-html.log
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 11, in <module>
    load_entry_point('Sphinx==2.2.0', 'console_scripts', 'sphinx-build')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 27, in <module>
    from sphinx.config import Config
  File "/usr/lib/python3.7/site-packages/sphinx/config.py", line 23, in <module>
    from sphinx.util.i18n import format_date
  File "/usr/lib/python3.7/site-packages/sphinx/util/i18n.py", line 19, in <module>
    import babel.dates
  File "/usr/lib/python3.7/site-packages/babel/dates.py", line 29, in <module>
    from babel.util import UTC, LOCALTZ
  File "/usr/lib/python3.7/site-packages/babel/util.py", line 20, in <module>
    from babel import localtime
  File "/usr/lib/python3.7/site-packages/babel/localtime/__init__.py", line 74, in <module>
    LOCALTZ = get_localzone()
  File "/usr/lib/python3.7/site-packages/babel/localtime/__init__.py", line 70, in get_localzone
    return _get_localzone()
  File "/usr/lib/python3.7/site-packages/babel/localtime/_unix.py", line 125, in _get_localzone
    with open(tzpath, 'rb') as tzfile:
IsADirectoryError: [Errno 21] Is a directory: '/etc/localtime'
make[2]: *** [doc/CMakeFiles/doc_html.dir/build.make:58: doc/CMakeFiles/doc_html] Error 1
make[1]: *** [CMakeFiles/Makefile2:334: doc/CMakeFiles/doc_html.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

## Environment:

Arch Linux

## Additional context
I also tried installation instructions from markdown, and below is what output after I run 
```sudo make install```
```
Scanning dependencies of target doc_html
[  1%] sphinx-build html: see doc/builder-html.log
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 11, in <module>
    load_entry_point('Sphinx==2.2.0', 'console_scripts', 'sphinx-build')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 27, in <module>
    from sphinx.config import Config
  File "/usr/lib/python3.7/site-packages/sphinx/config.py", line 23, in <module>
    from sphinx.util.i18n import format_date
  File "/usr/lib/python3.7/site-packages/sphinx/util/i18n.py", line 19, in <module>
    import babel.dates
  File "/usr/lib/python3.7/site-packages/babel/dates.py", line 29, in <module>
    from babel.util import UTC, LOCALTZ
  File "/usr/lib/python3.7/site-packages/babel/util.py", line 20, in <module>
    from babel import localtime
  File "/usr/lib/python3.7/site-packages/babel/localtime/__init__.py", line 74, in <module>
    LOCALTZ = get_localzone()
  File "/usr/lib/python3.7/site-packages/babel/localtime/__init__.py", line 70, in get_localzone
    return _get_localzone()
  File "/usr/lib/python3.7/site-packages/babel/localtime/_unix.py", line 125, in _get_localzone
    with open(tzpath, 'rb') as tzfile:
IsADirectoryError: [Errno 21] Is a directory: '/etc/localtime'
make[2]: *** [doc/CMakeFiles/doc_html.dir/build.make:58: doc/CMakeFiles/doc_html] Error 1
make[1]: *** [CMakeFiles/Makefile2:334: doc/CMakeFiles/doc_html.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

**Comment by patrick96** [comment]
> IsADirectoryError: [Errno 21] Is a directory: '/etc/localtime'

This seems like an arch installation error on your side. `/etc/localtime` is generally a symlink not a directory. See the [Arch Wiki](https://wiki.archlinux.org/index.php/Installation_guide#Time_zone)
