### ISSUE TITLE
polybar/polybar-git installation: Error during build(): unpack requires a buffer of 44 bytes

### ISSUE THREAD

**Issue by datanev** [polybar/polybar#1930]
I'm getting this while trying to install polybar/polybar-git using trizen
I also tried compiling from source following the steps described [here](https://github.com/polybar/polybar#building-from-source), but with the same error.
Fresh Arch Linux installation with i3-gaps (tried with i3-wm, same thing).
Let me know if you need any more information

```
Scanning dependencies of target doc_html
[  1%] sphinx-build html: see doc/builder-html.log
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 11, in <module>
    load_entry_point('Sphinx==2.2.0', 'console_scripts', 'sphinx-build')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 27, in <module>
    from sphinx.config import Config
  File "/usr/lib/python3.7/site-packages/sphinx/config.py", line 23, in <module>
    from sphinx.util.i18n import format_date
  File "/usr/lib/python3.7/site-packages/sphinx/util/i18n.py", line 19, in <module>
    import babel.dates
  File "/usr/lib/python3.7/site-packages/babel/dates.py", line 29, in <module>
    from babel.util import UTC, LOCALTZ
  File "/usr/lib/python3.7/site-packages/babel/util.py", line 20, in <module>
    from babel import localtime
  File "/usr/lib/python3.7/site-packages/babel/localtime/__init__.py", line 74, in <module>
    LOCALTZ = get_localzone()
  File "/usr/lib/python3.7/site-packages/babel/localtime/__init__.py", line 70, in get_localzone
    return _get_localzone()
  File "/usr/lib/python3.7/site-packages/babel/localtime/_unix.py", line 126, in _get_localzone
    return pytz.tzfile.build_tzinfo('local', tzfile)
  File "/usr/lib/python3.7/site-packages/pytz/tzfile.py", line 29, in build_tzinfo
    typecnt, charcnt) = unpack(head_fmt, fp.read(head_size))
struct.error: unpack requires a buffer of 44 bytes
make[2]: *** [doc/CMakeFiles/doc_html.dir/build.make:58: doc/CMakeFiles/doc_html] Error 1
make[1]: *** [CMakeFiles/Makefile2:324: doc/CMakeFiles/doc_html.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: Unable to build polybar-git - makepkg exited with code: 4
```

**Comment by patrick96** [comment]
Hmm, I couldn't this reproduce on my end. Could you please post the entire output of `makepkg`

**Comment by datanev** [comment]
```
Switched to a new branch 'makepkg'
==> Starting prepare()...
==> Starting pkgver()...
==> Updated version: polybar-git 3.4.0.r36.g7ee6093a-1
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- No build type specified; using Release
-- Using supported compiler GNU-9.2.0
--  Build:
--    Version: 3.4.0-36-g7ee6093a
--    Type: Release
--    CXX: /usr/bin/c++ -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
--    LD: /usr/bin/ld -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
--  Install Paths:
--    PREFIX:  /usr
--    BINDIR:  /usr/bin
--    DATADIR: /usr/share
--    DOCDIR:  /usr/share/doc/polybar
--    MANDIR:  /usr/share/man
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
-- [X]   documentation
--  Module support:
-- [X]   alsa (1.1.9)
-- [X]   curl (7.66.0)
-- [X]   i3
-- [X]   mpd (2.16)
-- [X]   network (libnl) (3.5.0)
-- [X]   pulseaudio (13.0-dirty)
-- [X]   xkeyboard (1.13.1)
--  X extensions:
-- [X]   xcb-randr (1.13.1)
-- [X]   xcb-randr (monitor support) (1.13.1)
-- [X]   xcb-composite (1.13.1)
-- [X]   xcb-xkb (1.13.1)
-- [X]   xcb-xrm (1.3)
-- [X]   xcb-cursor (0.1.3)
--  Log options:
-- [X]   Trace logging
-- XCB[XCB]: Found component XCB
-- XCB[ICCCM]: Found component ICCCM
-- XCB[EWMH]: Found component EWMH
-- XCB[UTIL]: Found component UTIL
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so  
-- Searching for xcbgen with python
-- Found xcbgen in /usr/lib/python3.7/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so  
-- XCB[COMPOSITE]: Found component COMPOSITE
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so;/usr/lib/libxcb-composite.so  
-- XCB[XKB]: Found component XKB
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so;/usr/lib/libxcb-composite.so;/usr/lib/libxcb-xkb.so  
-- xpp: including xcb proto composite.xml
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Found font: misc fixed:pixelsize=10
-- Found font: unifont:fontformat=truetype
-- Found font: siji:pixelsize=10
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/trizen-raindrops/polybar-git/src/polybar/build
[  1%] sphinx-build html: see doc/builder-html.log
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 11, in <module>
    load_entry_point('Sphinx==2.2.0', 'console_scripts', 'sphinx-build')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 27, in <module>
    from sphinx.config import Config
  File "/usr/lib/python3.7/site-packages/sphinx/config.py", line 23, in <module>
    from sphinx.util.i18n import format_date
  File "/usr/lib/python3.7/site-packages/sphinx/util/i18n.py", line 19, in <module>
    import babel.dates
  File "/usr/lib/python3.7/site-packages/babel/dates.py", line 29, in <module>
    from babel.util import UTC, LOCALTZ
  File "/usr/lib/python3.7/site-packages/babel/util.py", line 20, in <module>
    from babel import localtime
  File "/usr/lib/python3.7/site-packages/babel/localtime/__init__.py", line 74, in <module>
    LOCALTZ = get_localzone()
  File "/usr/lib/python3.7/site-packages/babel/localtime/__init__.py", line 70, in get_localzone
    return _get_localzone()
  File "/usr/lib/python3.7/site-packages/babel/localtime/_unix.py", line 126, in _get_localzone
    return pytz.tzfile.build_tzinfo('local', tzfile)
  File "/usr/lib/python3.7/site-packages/pytz/tzfile.py", line 29, in build_tzinfo
    typecnt, charcnt) = unpack(head_fmt, fp.read(head_size))
struct.error: unpack requires a buffer of 44 bytes
make[2]: *** [doc/CMakeFiles/doc_html.dir/build.make:58: doc/CMakeFiles/doc_html] Error 1
make[1]: *** [CMakeFiles/Makefile2:324: doc/CMakeFiles/doc_html.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: Unable to build polybar-git - makepkg exited with code: 4
```

There you go! Let me know if there's anything else I can post

**Comment by patrick96** [comment]
Seems you have not setup your timezone correctly. `/etc/localtime` should be a symlink to a file in `/usr/share/zoneinfo`: https://wiki.archlinux.org/index.php/Installation_guide#Time_zone

**Comment by datanev** [comment]
That was it! Thank you so much!
