### ISSUE TITLE
Build failure with polybar-3.4.1, xpp-1.4.0, i3ipcpp-0.7.1

### ISSUE THREAD

**Issue by ajakk** [polybar/polybar#1944]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*

```
$ git clone https://github.com/polybar/polybar --recursive
# Grab latest release versions of xpp, i3ipcpp, polybar
$ cd polybar/lib/xpp && git checkout 1.4.0
$ cd ../i3ipcpp && git checkout v0.7.1
$ cd ../.. && git checkout 3.4.1
$ mkdir build && cd build && cmake ..
$ make
```

**If you build polybar directly from this repository:**

* Output of `git describe --tags`:

`3.4.1`

*List exactly where you are building from and which version you are building.*

polybar-3.4.1, with xpp at 1.4.0 and i3ipcpp at v0.7.1. All latest release versions.

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*
```
$ cmake .. # From `build` directory
-- Trying to enable ccache
-- [32mUsing compiler cache /usr/bin/ccache[0m
-- The CXX compiler identification is GNU 9.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [33mNo build type specified; using Release[0m
-- [32mUsing supported compiler GNU-9.2.0[0m
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.16.0
-- Checking for module 'alsa'
--   Found alsa, version 1.2.1.1
-- Checking for module 'libcurl'
--   Found libcurl, version 7.67.0
-- Checking for module 'libmpdclient'
--   Found libmpdclient, version 2.16
-- Checking for module 'libnl-genl-3.0'
--   Found libnl-genl-3.0, version 3.5.0
-- Checking for module 'libpulse'
--   Found libpulse, version 13.0
-- Checking for module 'xcb-composite'
--   Found xcb-composite, version 1.13.1
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.13.1
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.13.1
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.13.1
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.3
-- Checking for module 'xcb-cursor'
--   Found xcb-cursor, version 0.1.3
--  Build:
-- [32;1m   Version: 3.4.1-dev[0m
-- [37;2m   Type: Release[0m
-- [37;2m   CXX: /usr/bin/c++  -Wall -Wextra -Wpedantic -O3 -DNDEBUG[0m
-- [37;2m   LD: /usr/bin/ld  [0m
--  Install Paths:
-- [32m   PREFIX:  /usr/local[0m
-- [32m   BINDIR:  /usr/local/bin[0m
-- [32m   DATADIR: /usr/local/share[0m
-- [32m   DOCDIR:  /usr/local/share/doc/polybar[0m
-- [32m   MANDIR:  /usr/local/share/man[0m
--  Targets:
-- [32;1m[X]   polybar-msg[0m
-- [37;2m[ ]   testsuite[0m
-- [32;1m[X]   documentation[0m
--  Module support:
-- [32;1m[X]   alsa (1.2.1.1)[0m
-- [32;1m[X]   curl (7.67.0)[0m
-- [32;1m[X]   i3[0m
-- [32;1m[X]   mpd (2.16)[0m
-- [32;1m[X]   network (libnl) (3.5.0)[0m
-- [32;1m[X]   pulseaudio (13.0)[0m
-- [32;1m[X]   xkeyboard (1.13.1)[0m
--  X extensions:
-- [32;1m[X]   xcb-randr (1.13.1)[0m
-- [32;1m[X]   xcb-randr (monitor support) (1.13.1)[0m
-- [32;1m[X]   xcb-composite (1.13.1)[0m
-- [32;1m[X]   xcb-xkb (1.13.1)[0m
-- [32;1m[X]   xcb-xrm (1.3)[0m
-- [32;1m[X]   xcb-cursor (0.1.3)[0m
--  Log options:
-- [32;1m[X]   Trace logging[0m
-- The C compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.13
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.17", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib64/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib64/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib64/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib64/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib64/libxcb-image.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so  
-- Searching for xcbgen with python2
-- Found xcbgen in /usr/lib64/python2.7/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib64/libxcb-randr.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so;/usr/lib64/libxcb-randr.so  
-- XCB[COMPOSITE]: Found component COMPOSITE
-- Found XCB_COMPOSITE: /usr/lib64/libxcb-composite.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so;/usr/lib64/libxcb-randr.so;/usr/lib64/libxcb-composite.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib64/libxcb-xkb.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so;/usr/lib64/libxcb-randr.so;/usr/lib64/libxcb-composite.so;/usr/lib64/libxcb-xkb.so  
-- xpp: including xcb proto composite.xml
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Checking for module 'jsoncpp>=1.7.7'
--   Found jsoncpp, version 1.9.2
-- Found font: fixed:pixelsize=10
-- [33;1mFont not found: unifont:fontformat=truetype[0m
-- Found font: wuncon siji:pixelsize=10
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jake/Programs/polybar/build
```
```
$ make
Scanning dependencies of target doc_html
[  1%] sphinx-build html: see doc/builder-html.log
WARNING: html_static_path entry '/home/jake/Programs/polybar/doc/_static' does not exist
[  1%] Built target doc_html
Scanning dependencies of target doc_man
[  2%] sphinx-build man: see doc/builder-man.log
[  2%] Built target doc_man
Scanning dependencies of target doc
[  2%] Built target doc
Scanning dependencies of target xpp
[  3%] Linking CXX static library libxpp.a
Traceback (most recent call last):
  File "/home/jake/Programs/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
    from xcbgen.state import Module
  File "/usr/lib64/python2.7/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib64/python2.7/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib64/python2.7/site-packages/xcbgen/xtypes.py", line 1221, in <module>
    class EventStruct(Union):
  File "/usr/lib64/python2.7/site-packages/xcbgen/xtypes.py", line 1239, in EventStruct
    out = __main__.output['eventstruct']
KeyError: 'eventstruct'
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:70: lib/xpp/libxpp.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:477: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

## Environment:
* Distro (with Version):
Gentoo

## Additional context
*Add any other context that you think is necessary about the problem here.*
The build works fine if polybar, xpp, and i3ipcpp are a ttheir newest commits. It seems that something changed with xpp since its release 1.4.0 and that fixes this breakage. An easy remedy would seem to be a version bump of xpp.

**Comment by patrick96** [comment]
That's not how you build polybar. Please follow the instructions on the wiki. For tagged releases there are release tar balls [here](https://github.com/polybar/polybar/releases).

A certain polybar commit or version is only guaranteed to work the the specific i3ipcpp and xpp commit which it is associated with (via git submodules). So manually checking out different commits in those submodules is not advised. If you want to make sure that the submodules are at the right commit, run `git submodule update --init --recursive` after checking out a new polybar branch or commit.
