### ISSUE TITLE
Qubes Polybar (Dom0 Fedora-25) build  issue.

### ISSUE THREAD

**Issue by 0rb677** [polybar/polybar#2004]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*
All above dependencies from here
https://github.com/polybar/polybar/wiki/Compiling#compiling

```
git clone --recursive https://github.com/polybar/polybar
tar cvf polybar.tar polybar/
qvm-run --pass-io untrusted 'cat /home/user/polybar.tar' > polybar.tar
tar xvf polybar.tar
cd polybar/
mkdir build
cd build
cmake ..
make -j$(nproc)
sudo make install
```

**If you build polybar directly from this repository:**

* Output of `git describe --tags`:
```
git describe --tags
3.4.0-69-g8d07f2a

```
**If you use some other way (like the AUR):**

*List exactly where you are building from and which version you are building.*

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*
```
[dom0 build]$ cmake ..
-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- The CXX compiler identification is GNU 6.4.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could not detect version with git, falling back to built-in version information.
-- No build type specified; using Release
-- Using supported compiler GNU-6.4.1
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.14.8
-- Checking for module 'alsa'
--   Found alsa, version 1.1.1
-- Checking for module 'libcurl'
--   Found libcurl, version 7.51.0
-- Checking for module 'libmpdclient'
--   Found libmpdclient, version 2.9
-- Checking for module 'libnl-genl-3.0'
--   Found libnl-genl-3.0, version 3.2.29
-- Checking for module 'libpulse'
--   Found libpulse, version 10.0
-- Checking for module 'xcb-composite'
--   Found xcb-composite, version 1.12
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.12
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.12
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.12
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.2
-- Checking for module 'xcb-cursor'
--   Found xcb-cursor, version 0.1.3
--  Build:
--    Version: 3.4.0
--    Type: Release
--    CXX: /usr/bin/c++  -Wall -Wextra -Wpedantic -O2 -DNDEBUG
--    LD: /usr/bin/ld  
--  Install Paths:
--    PREFIX:  /usr/local
--    BINDIR:  /usr/local/bin
--    DATADIR: /usr/local/share
--    DOCDIR:  /usr/local/share/doc/polybar
--    MANDIR:  /usr/local/share/man
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
-- [X]   documentation
--  Module support:
-- [X]   alsa (1.1.1)
-- [X]   curl (7.51.0)
-- [X]   i3
-- [X]   mpd (2.9)
-- [X]   network (libnl) (3.2.29)
-- [X]   pulseaudio (10.0)
-- [X]   xkeyboard (1.12)
--  X extensions:
-- [X]   xcb-randr (1.12)
-- [X]   xcb-randr (monitor support) (1.12)
-- [X]   xcb-composite (1.12)
-- [X]   xcb-xkb (1.12)
-- [X]   xcb-xrm (1.2)
-- [X]   xcb-cursor (0.1.3)
--  Log options:
-- [X]   Trace logging
-- The C compiler identification is GNU 6.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.12
-- Found PythonInterp: /usr/bin/python3.5 (found suitable version "3.5.4", minimum required is "3.5") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib64/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib64/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib64/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib64/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib64/libxcb-image.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so  
-- Searching for xcbgen with python
-- Found xcbgen in /usr/lib/python2.7/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib64/libxcb-randr.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so;/usr/lib64/libxcb-randr.so  
-- XCB[COMPOSITE]: Found component COMPOSITE
-- Found XCB_COMPOSITE: /usr/lib64/libxcb-composite.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so;/usr/lib64/libxcb-randr.so;/usr/lib64/libxcb-composite.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib64/libxcb-xkb.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so;/usr/lib64/libxcb-randr.so;/usr/lib64/libxcb-composite.so;/usr/lib64/libxcb-xkb.so  
-- xpp: including xcb proto composite.xml
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Checking for module 'jsoncpp>=1.7.7'
--   Found jsoncpp, version 1.8.1
-- Font not found: fixed:pixelsize=10
-- Found font: unifont:fontformat=truetype
-- Found font: siji:pixelsize=10
-- Configuring done
-- Generating done
-- Build files have been written to: /home/0rb/polybar/build
[0rb@dom0 build]$ make
Scanning dependencies of target doc_man
[  1%] sphinx-build man: see doc/builder-man.log
[  1%] Built target doc_man
Scanning dependencies of target doc_html
[  2%] sphinx-build html: see doc/builder-html.log
WARNING: html_static_path entry '/home/0rb/polybar/doc/_static' does not exist
[  2%] Built target doc_html
Scanning dependencies of target doc
[  2%] Built target doc
[  3%] Generating ../../../lib/xpp/include/xpp/proto/x.hpp
Traceback (most recent call last):
  File "/home/0rb/polybar/lib/xpp/generators/cpp_client.py", line 3101, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python2.7/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python2.7/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python2.7/site-packages/xcbgen/xtypes.py", line 504
    print "Explicit start-align for %s: %s\n" % (self, self.required_start_align)
                                            ^
SyntaxError: invalid syntax
lib/xpp/CMakeFiles/xpp.dir/build.make:73: recipe for target '../lib/xpp/include/xpp/proto/x.hpp' failed
make[2]: *** [../lib/xpp/include/xpp/proto/x.hpp] Error 1
make[2]: *** Deleting file '../lib/xpp/include/xpp/proto/x.hpp'
CMakeFiles/Makefile2:506: recipe for target 'lib/xpp/CMakeFiles/xpp.dir/all' failed
make[1]: *** [lib/xpp/CMakeFiles/xpp.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

## Environment:
Qubes OS R 4.0

## Additional context
Trying with Clang, no success.

**Comment by patrick96** [comment]
The `xcb-proto` package in your distro still uses python2. We no longer support python2 because support for python2 ended at the end of 2019.

Find a way to install an `xcb-proto` package that uses python3 and this should work. But I really suggest you update fedora because Fedora 25 is also no longer supported since the end of 2017.

**Comment by fepitre** [comment]
Have a look here: https://github.com/QubesOS/qubes-issues/issues/5624
I already fixed those troubles when packaging them for R4.0. Indeed, with newer Qubes R4.1 based on Fedora 31 those packages would be already in Fedora repositories.
