### ISSUE TITLE
SIGSEGV in xworkspaces and hot-(un)plugging 2nd monitor

### ISSUE THREAD

**Issue by skrat** [polybar/polybar#2048]
I'm trying to get polybar play nicely with hot plugging/unplugging 2nd monitor in i3(-gaps) and autorandr. So when I connect it, i3 creates new workspace there. That workspace is empty (has no windows) but it exists regardless because that's what i3 does. Otherwise i3 doesn't keep empty workspaces unless they're "active". When I disconnect 2nd monitor, and that workspace that was there was empty, it is destroyed by i3. If there would be any windows, i3 would move the workspace to the 1st output. Either way, there's something off in the workspaces modules. See below

```
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	    ____        __      __
;;	   / __ \____  / /_  __/ /_  ____ ______
;;	  / /_/ / __ \/ / / / / __ \/ __ `/ ___/
;;	 / ____/ /_/ / / /_/ / /_/ / /_/ / /
;;	/_/    \____/_/\__, /_.___/\__,_/_/
;;	              /____/
;;
;; Created By Aditya Shakya @adi1090x
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Global WM Settings

[global/wm]
; Adjust the _NET_WM_STRUT_PARTIAL top value
; Used for top aligned bars
margin-bottom = 0

; Adjust the _NET_WM_STRUT_PARTIAL bottom value
; Used for bottom aligned bars
margin-top = 0

;; Bar Settings

[bar/main]
; Use either of the following command to list available outputs:
; If unspecified, the application will pick the first one it finds.
; $ polybar -m | cut -d ':' -f 1
; $ xrandr -q | grep " connected" | cut -d ' ' -f1
monitor = LVDS1

; Use the specified monitor as a fallback if the main one is not found.
monitor-fallback = LVDS1

; Require the monitor to be in connected state
; XRandR sometimes reports my monitor as being disconnected (when in use)
monitor-strict = true

; Tell the Window Manager not to configure the window.
; Use this to detach the bar if your WM is locking its size/position.
override-redirect = true

; Put the bar at the bottom of the screen
bottom = false

; Prefer fixed center position for the `modules-center` block
; When false, the center position will be based on the size of the other blocks.
fixed-center = true

; Dimension defined as pixel value (e.g. 35) or percentage (e.g. 50%),
; the percentage can optionally be extended with a pixel offset like so:
; 50%:-10, this will result in a width or height of 50% minus 10 pixels
width = 100%
height = 26

; Offset defined as pixel value (e.g. 35) or percentage (e.g. 50%)
; the percentage can optionally be extended with a pixel offset like so:
; 50%:-10, this will result in an offset in the x or y direction
; of 50% minus 10 pixels
offset-x = 0
offset-y = 0

; Background ARGB color (e.g. #f00, #ff992a, #ddff1023)
background = ${color.bg}

; Foreground ARGB color (e.g. #f00, #ff992a, #ddff1023)
foreground = ${color.fg}

; Background gradient (vertical steps)
;   background-[0-9]+ = #aarrggbb
;;background-0 =

; Value used for drawing rounded corners
; Note: This shouldn't be used together with border-size because the border
; doesn't get rounded
; Individual top/bottom values can be defined using:
;   radius-{top,bottom}
radius-top = 0.0
radius-bottom = 0.0

; Under-/overline pixel size and argb color
; Individual values can be defined using:
;   {overline,underline}-size
;   {overline,underline}-color
;;overline-size = 0
;;overline-color = ${color.ac}

; Values applied to all borders
; Individual side values can be defined using:
;   border-{left,top,right,bottom}-size
;   border-{left,top,right,bottom}-color
; The top and bottom borders are added to the bar height, so the effective
; window height is:
;   height + border-top-size + border-bottom-size
; Meanwhile the effective window width is defined entirely by the width key and
; the border is placed withing this area. So you effectively only have the
; following horizontal space on the bar:
;   width - border-right-size - border-left-size
;;border-size = 2
;;border-color = ${color.ac}

; Number of spaces to add at the beginning/end of the bar
; Individual side values can be defined using:
;   padding-{left,right}
padding-left = 2
padding-right = 4

; Number of spaces to add before/after each module
; Individual side values can be defined using:
;   module-margin-{left,right}
module-margin-left = 3
module-margin-right = 3

; Fonts are defined using <font-name>;<vertical-offset>
; Font names are specified using a fontconfig pattern.
;   font-0 = NotoSans-Regular:size=8;2
;   font-1 = MaterialIcons:size=10
;   font-2 = Termsynu:size=8;-1
;   font-3 = FontAwesome:size=10
; See the Fonts wiki page for more details

font-0 = "Droid Sans:size=9:weight=bold;2"
font-1 = "Iosevka Nerd Font:size=12;2"

; Modules are added to one of the available blocks
;   modules-left = cpu ram
;   modules-center = xwindow xbacklight
;   modules-right = ipc clock

modules-left = workspaces
modules-center = date
modules-right = alsa network battery sysmenu

; The separator will be inserted between the output of each module
separator =

; Opacity value between 0.0 and 1.0 used on fade in/out
dim-value = 1.0

; Value to be used to set the WM_NAME atom
; If the value is empty or undefined, the atom value
; will be created from the following template: polybar-[BAR]_[MONITOR]
; NOTE: The placeholders are not available for custom values
wm-name =

; Locale used to localize various module data (e.g. date)
; Expects a valid libc locale, for example: sv_SE.UTF-8
locale =

; Position of the system tray window
; If empty or undefined, tray support will be disabled
; NOTE: A center aligned tray will cover center aligned modules
;
; Available positions:
;   left
;   center
;   right
;   none
tray-position = right

; If true, the bar will not shift its
; contents when the tray changes
tray-detached = false

; Tray icon max size
tray-maxsize = 16

; Background color for the tray container
; ARGB color (e.g. #f00, #ff992a, #ddff1023)
; By default the tray container will use the bar
; background color.
tray-background = ${root.background}

; Tray offset defined as pixel value (e.g. 35) or percentage (e.g. 50%)
tray-offset-x = 0
tray-offset-y = 0

; Pad the sides of each tray icon
tray-padding = 0

; Scale factor for tray clients
tray-scale = 1.0

; Restack the bar window and put it above the
; selected window manager's root
;
; Fixes the issue where the bar is being drawn
; on top of fullscreen window's
;
; Currently supported WM's:
;   bspwm
;   i3 (requires: `override-redirect = true`)
wm-restack = i3

; Set a DPI values used when rendering text
; This only affects scalable fonts
; dpi =

; Enable support for inter-process messaging
; See the Messaging wiki page for more details.
enable-ipc = true

; Fallback click handlers that will be called if
; there's no matching module handler found.
click-left =
click-middle =
click-right =
double-click-left =
double-click-middle =
double-click-right =

; Requires polybar to be built with xcursor support (xcb-util-cursor)
; Possible values are:
; - default   : The default pointer as before, can also be an empty string (default)
; - pointer   : Typically in the form of a hand
; - ns-resize : Up and down arrows, can be used to indicate scrolling
cursor-click =
cursor-scroll =

;; WM Workspace Specific

; bspwm
;;scroll-up = bspwm-desknext
;;scroll-down = bspwm-deskprev
;;scroll-up = bspc desktop -f prev.local
;;scroll-down = bspc desktop -f next.local

;i3
scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev
;;scroll-up = i3-msg workspace next_on_output
;;scroll-down = i3-msg workspace prev_on_output

;openbox
;awesome
;etc

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Application Settings

[settings]
; The throttle settings lets the eventloop swallow up til X events
; if they happen within Y millisecond after first event was received.
; This is done to prevent flood of update event.
;
; For example if 5 modules emit an update event at the same time, we really
; just care about the last one. But if we wait too long for events to swallow
; the bar would appear sluggish so we continue if timeout
; expires or limit is reached.
throttle-output = 5
throttle-output-for = 10

; Time in milliseconds that the input handler will wait between processing events
throttle-input-for = 30

; Reload upon receiving XCB_RANDR_SCREEN_CHANGE_NOTIFY events
screenchange-reload = true

; Compositing operators
; @see: https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-operator-t
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

; Define fallback values used by all module formats
format-foreground =
format-background =
format-underline =
format-overline =
format-spacing =
format-padding =
format-margin =
format-offset =

; Enables pseudo-transparency for the bar
; If set to true the bar can be transparent without a compositor.
pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	   ______      __
;;	  / ____/___  / /___  __________
;;	 / /   / __ \/ / __ \/ ___/ ___/
;;	/ /___/ /_/ / / /_/ / /  (__  )
;;	\____/\____/_/\____/_/  /____/
;;
;; Created By Aditya Shakya @adi1090x
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Active Colors
bg = #00000000
fg = #EAEAEA
fg-alt = #9C9C9C

trans = #00000000
white = #FFFFFF
black = #000000

;; Material Colors

red = #e53935
pink = #d81b60
purple = #8e24aa
deep-purple = #5e35b1
indigo = #3949ab
blue = #1e88e5
light-blue = #039be5
cyan = #00acc1
teal = #00897b
green = #43a047
light-green = #7cb342
lime = #c0ca33
yellow = #fdd835
amber = #ffb300
orange = #fb8c00
deep-orange = #f4511e
brown = #6d4c41
grey = #757575
blue-gray = #546e7a

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	    __  ___          __      __
;;	   /  |/  /___  ____/ /_  __/ /__  _____
;;	  / /|_/ / __ \/ __  / / / / / _ \/ ___/
;;	 / /  / / /_/ / /_/ / /_/ / /  __(__  )
;;	/_/  /_/\____/\__,_/\__,_/_/\___/____/
;;
;; Created By Aditya Shakya @adi1090x
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/alsa]
type = internal/alsa

; You can find the different card numbers in `/proc/asound/cards`
;;master-soundcard = default
;;speaker-soundcard = default
;;headphone-soundcard = default

; Default: Master
;;master-mixer = Master

; Optionally define speaker and headphone mixers
; Default: none
;;speaker-mixer = Speaker
; Default: none
;;headphone-mixer = Headphone

; Default: 5
;;interval = 5

; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <ramp-volume>

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
;format-muted = <label-muted>

; Available tokens:
;   %percentage% (default)
label-volume = %percentage%%

; Available tokens:
;   %percentage% (default
label-muted = ﱝ
label-muted-foreground = ${color.fg-alt}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery]
type = internal/battery

full-at = 99

; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC

poll-interval = 2
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <label-charging> <animation-charging>

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <label-discharging> <ramp-capacity>

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
;format-full = <ramp-capacity> <label-full>

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = %percentage%%

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = %percentage%%

; Available tokens:
;   %percentage% (default)
;label-full = Fully Charged
label-full = 
label-full-foreground = ${color.green}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 

; Framerate in milliseconds
animation-charging-framerate = 750

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date

interval = 1.0

time = "%a %b %d    %I:%M %p"
;time-alt = %B %d, %Y

format = <label>
label = %time%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/network]
type = internal/network

interface = wlp3s0
interval = 1.0

;ping-interval = 3
;;udspeed-minwidth = 5
accumulate-stats = true
unknown-as-up = true

; Available tags:
;   <label-connected> (default)
;   <ramp-signal>
format-connected = <ramp-signal>

; Available tags:
;   <label-disconnected> (default)
format-disconnected = <label-disconnected>

; Available tags:
;   <label-connected> (default)
;   <label-packetloss>
;   <animation-packetloss>
;;format-packetloss = <animation-packetloss> <label-connected>

; Available tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %linkspeed% [wired]
; Default: %ifname% %local_ip%
label-connected = %downspeed%

; Available tokens:
;   %ifname%    [wireless+wired]
; Default: (none)
label-disconnected = 睊
label-disconnected-foreground = ${color.fg-alt}

; Available tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %linkspeed% [wired]
; Default: (none)
;label-packetloss = %essid%
;label-packetloss-foreground = #eefafafa

ramp-signal-0 = 直
ramp-signal-1 = 直
ramp-signal-2 = 直
ramp-signal-3 = 直
ramp-signal-4 = 直

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/applications]
type = custom/text

content = Applications
;;content-background = ${color.bg}
content-foreground = ${color.fg}
;;content-padding = 4

click-left = ~/.config/polybar/scripts/elementary-menu
click-right = ~/.config/polybar/scripts/elementary-menu

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sysmenu]
type = custom/text

content = 襤
;;content-background = ${color.bg}
content-foreground = ${color.fg}
;;content-padding = 4

click-left = ~/.config/polybar/scripts/elementary-sysmenu
click-right = ~/.config/polybar/scripts/elementary-sysmenu

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/style]
type = custom/text
content = 

click-left = ~/.config/polybar/scripts/elementary-style &
click-right = ~/.config/polybar/scripts/elementary-style &

[module/i3]
type = internal/i3

; Only show workspaces defined on the same output as the bar
;
; Useful if you want to show monitor specific workspaces
; on different bars
;
; Default: false
pin-workspaces = true

; This will split the workspace name on ':'
; Default: false
strip-wsnumbers = true

; Sort the workspaces by index instead of the default
; sorting that groups the workspaces by output
; Default: false
index-sort = true

; Create click handler used to focus workspace
; Default: true
enable-click = false

; Create scroll handlers used to cycle workspaces
; Default: true
enable-scroll = false

; Wrap around when reaching the first/last workspace
; Default: true
wrapping-scroll = false

; Set the scroll cycle direction
; Default: true
reverse-scroll = false

; Use fuzzy (partial) matching on labels when assigning
; icons to workspaces
; Example: code;♚ will apply the icon to all workspaces
; containing 'code' in the label
; Default: false
fuzzy-match = true

[module/workspaces]
type = internal/xworkspaces
pin-workspaces = false
enable-click = true
enable-scroll = true
format-padding = 1

;icon-0 = 1;❶
;icon-1 = 2;❷
;icon-2 = 3;❸
;icon-3 = 4;❹
;icon-4 = 5;❺
;icon-5 = 6;❻
;icon-6 = 7;❼
;icon-7 = 8;❽
;icon-8 = 9;❾
;icon-9 = 10;❿

icon-default = 

format = <label-state>
format-background = ${color.bg}
label-active = 
label-occupied = 
label-urgent = 
label-empty = 

label-empty-padding = 1
label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1

label-empty-foreground = ${color.fg}
label-active-foreground = ${color.fg}
label-urgent-foreground = ${color.orange}
label-occupied-foreground = ${color.pink}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;	    __________  ______
;;	   / ____/ __ \/ ____/
;;	  / __/ / / / / /_
;;	 / /___/ /_/ / __/
;;	/_____/\____/_/
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

```

----------------------------

```
 Redrawing bar window
* module/network: Rebuilding cache
* module/battery: Rebuilding cache
* module/workspaces: Rebuilding cache
* Redrawing bar window
* module/workspaces: Rebuilding cache
* Redrawing bar window
* module/battery: Polling values (inotify fallback)
* module/workspaces: Rebuilding cache
* Redrawing bar window
* module/workspaces: Rebuilding cache
* Redrawing bar window
* module/network: Rebuilding cache
* module/battery: Rebuilding cache
* module/battery: Rebuilding cache
* module/network: Rebuilding cache
* module/battery: Rebuilding cache
* module/network: Rebuilding cache
* module/battery: Rebuilding cache
* module/battery: Polling values (inotify fallback)
* module/network: Rebuilding cache
* module/battery: Rebuilding cache
warn: randr_screen_change_notify (3520x1080)... reloading

Thread 1 "polybar" received signal SIGUSR1, User defined signal 1.
0x00007ffff714a685 in raise () from /usr/lib/libpthread.so.0
(gdb) 
Continuing.
[Thread 0x7fffc7fff700 (LWP 337389) exited]
warn: Termination signal received, shutting down...
* module/workspaces: Stopping
* Deconstruction of module/workspaces took 0 ms.
* module/date: Stopping
* Deconstruction of module/date took 0 ms.
* module/alsa: Stopping
[Thread 0x7fffdf7fe700 (LWP 337383) exited]
[Thread 0x7fffdeffd700 (LWP 337384) exited]
[Thread 0x7ffff0bdf700 (LWP 337381) exited]
* Deconstruction of module/alsa took 4 ms.
* module/network: Stopping
* Deconstruction of module/network took 0 ms.
* module/battery: Stopping
[Thread 0x7fffde7fc700 (LWP 337385) exited]
* Deconstruction of module/battery took 258 ms.
* module/sysmenu: Stopping
[Thread 0x7fffdd7fa700 (LWP 337387) exited]
* Deconstruction of module/sysmenu took 0 ms.
[Thread 0x7fffddffb700 (LWP 337386) exited]
[Thread 0x7ffff53e0700 (LWP 337380) exited]
* Deactivating tray manager
* Waiting for spawned processes to end
* Re-launching application...
process 337327 is executing new program: /usr/bin/polybar
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
* Loading config: /home/skrat/.config/polybar/config.ini
* Created ipc channel at: /tmp/polybar_mqueue.337327
[New Thread 0x7ffff53e0700 (LWP 337415)]
* Loaded monitor LVDS1 (1600x900+1920+0)
* Bar geometry: 1600x26+1920+0; Borders: 0,0,0,0
[New Thread 0x7ffff0bdf700 (LWP 337416)]
* Starting application
* Starting module/workspaces
[New Thread 0x7fffdffff700 (LWP 337417)]
* Starting module/date
[New Thread 0x7fffdf7fe700 (LWP 337418)]
[Thread 0x7fffdffff700 (LWP 337417) exited]
* Starting module/alsa
[New Thread 0x7fffdeffd700 (LWP 337419)]
* Starting module/network
[New Thread 0x7fffde7fc700 (LWP 337420)]
* Starting module/battery
[New Thread 0x7fffddffb700 (LWP 337421)]
[New Thread 0x7fffdd7fa700 (LWP 337422)]
* Starting module/sysmenu
[New Thread 0x7fffdcff9700 (LWP 337423)]
[New Thread 0x7fffcffff700 (LWP 337424)]
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=8)
[Thread 0x7fffdcff9700 (LWP 337423) exited]
* Configured DPI = 96x96
* Loaded font "Droid Sans:size=9:weight=bold" (name=Droid Sans, offset=2, file=/usr/share/fonts/OpenImageIO/DroidSans-Bold.ttf)
* Loaded font "Iosevka Nerd Font:size=12" (name=Iosevka, offset=2, file=/home/skrat/.local/share/fonts/IosevkaNerdFont-Complete.ttf)
* Bar window: 0x0800002
* Successfully restacked bar window
* Activating tray manager
* Tray window: 0x0800006
[New Thread 0x7fffcf7fe700 (LWP 337425)]
* module/workspaces: Rebuilding cache
* module/date: Rebuilding cache
* module/alsa: Rebuilding cache
* module/network: Rebuilding cache
* module/battery: Rebuilding cache
* module/sysmenu: Rebuilding cache
* Redrawing bar window
* module/network: Rebuilding cache
* module/battery: Rebuilding cache
* Notifying pending tray clients
[Thread 0x7fffcf7fe700 (LWP 337425) exited]
* module/network: Rebuilding cache
* module/battery: Rebuilding cache
* module/battery: Polling values (inotify fallback)
* module/workspaces: Rebuilding cache
* Redrawing bar window
* module/network: Rebuilding cache
* module/battery: Rebuilding cache

Thread 1 "polybar" received signal SIGSEGV, Segmentation fault.
0x00007ffff7018840 in __memmove_sse2_unaligned_erms () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7018840 in __memmove_sse2_unaligned_erms () from /usr/lib/libc.so.6
#1  0x00007ffff73fb176 in std::char_traits<char>::copy (__n=49, __s2=<optimized out>, __s1=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:365
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=49, 
    __s=<optimized out>, __d=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:351
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (
    this=0x555555870a68, __str=<error: Cannot access memory at address 0xe0>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:272
#4  0x00005555557577e2 in polybar::modules::xworkspaces_module::handle(xpp::x::event::property_notify<polybar::connection&> const&) ()
#5  0x0000555555778848 in bool xpp::x::event::dispatcher<polybar::connection&>::operator()<xpp::event::registry<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>::handler>(xpp::event::registry<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>::handler, std::shared_ptr<xcb_generic_event_t> const&) const ()
#6  0x0000555555773c19 in polybar::connection::dispatch_event(std::shared_ptr<xcb_generic_event_t> const&) const ()
#7  0x0000555555681adf in polybar::controller::read_events() ()
#8  0x0000555555688b96 in polybar::controller::run(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#9  0x0000555555636a15 in main ()
(gdb) 
```

**Comment by patrick96** [comment]
I'm guessing this happens consistently, right?

Unfortunately your polybar doesn't have debug symbols so the stack trace cannot tell us exactly where things went wrong. My guess is, it's in this piece of code where we may access an array out of bounds:

https://github.com/polybar/polybar/blob/15496bfb4a2fc0b3c8d966c0392a732e62c94aab/src/modules/xworkspaces.cpp#L109-L112

This would happen when `_NET_CURRENT_DESKTOP` is out of bounds of the desktop list we have internally.
Normally, whenever `_NET_NUMBER_OF_DESKTOPS` gets updated, we also update our list of desktop names and according to the spec `0 <= _NET_CURRENT_DESKTOP <= _NET_NUMBER_OF_DESKTOPS - 1`.

So either i3 is not compliant here and temporarily sets `_NET_CURRENT_DESKTOP` too high or the xworkspaces module has some false assumptions. Either way, polybar should never segfault.

I don't have time to look at this for at least two weeks, but in the meantime, if you can, please compile polybar with debug symbols (`cmake -DCMAKE_BUILD_TYPE=Debug ..`) and try to get that stacktrace again to confirm my suspicion.

**Comment by vaygr** [comment]
I can confirm this happens consistently, when I [un]plug my projector. Fluxbox  1.3.7 here.

I can probably look into it in the next couple of weeks to see what's going on.

**Comment by patrick96** [comment]
Appreciate it @vaygr :smiley:

**Comment by vaygr** [comment]
False alarm. It seems I confused it with polybar restarting itself. While debugging I got nothing more than USR1.

**Comment by patrick96** [comment]
@vaygr That's too bad :slightly_frowning_face: 

When not running in the debugger do you get a segfault then? Or how does it look like?

With `screenchange-reload` receiving `USR1` is normal, that's how polybar restarts itself. gdb will break here (even though we have our own signal handler), what happens when you run `continue` from there? Does it continue on normally?

**Comment by vaygr** [comment]
Yeah, it continues normally. It's just in the past I saw polybar crashing in similar circumstances, so I ran it in the WM via loop like this:

```shell
…
# --------+
# Fluxbox |

fluxbox -log ~/.xsession-errors &
fbpid=$!

fbautostart

sleep 1

{
	{ while :; do polybar -q top; done } &
	{ while :; do polybar -q bottom; done } &
	tilda &
	nall &
} &

wait $fbpid
```

It was a couple of years ago, but recently I've been confusing these crashes with polybar restarting itself.

**Comment by patrick96** [comment]
Oh, I see
