### ISSUE TITLE
Build error on Arch Linux: pkg_resources.DistributionNotFound: The 'alabaster<0.8,>=0.7' distribution was not found and is required by Sphinx

### ISSUE THREAD

**Issue by sflip** [polybar/polybar#2092]
I am getting a build error (since a few weeks) and reporting it here as requested in the README.
The error is about the transitive `alabaster` Python dependency of Sphinx.
It occurs both when I clone and build from source or when I use the AUR.

I'd be really happy if someone can help! Also, I wonder whether I am the only one with this problem.

## Build Process
*Describe how you build polybar, list the exact commands you are using:*
```
> mkdir build
> cd build
> cmake ..
> make -j$(nproc)
```
**If you build polybar directly from this repository:**

* Output of `git describe --tags`:
```
3.4.0-99-g92181fd
```
Build date: 2020-05-08
Version:
```
> git --no-pager log -n 1
commit 92181fd237e0d282a24df7e8afe11e420c8c174b (HEAD -> master, origin/master, origin/HEAD)
Author: patrick96 <p.ziegler96@gmail.com>
Date:   Wed May 6 21:09:02 2020 +0200

    build: Update xpp module

    Fixes developer warnings in cmake 3.17+

    Ref: polybar/xpp#24
    Ref: polybar/xpp#25
```

## Build Log
```
> mkdir build

> cd build/

> cmake ..
-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using Release
-- Using supported compiler GNU-9.3.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.17.3
-- Checking for module 'alsa'
--   Found alsa, version 1.2.2
-- Checking for module 'libcurl'
--   Found libcurl, version 7.70.0
-- Checking for module 'libmpdclient'
--   Found libmpdclient, version 2.18
-- Checking for module 'libnl-genl-3.0'
--   Found libnl-genl-3.0, version 3.5.0
-- Checking for module 'libpulse'
--   Found libpulse, version 13.0
-- Checking for module 'xcb-composite'
--   Found xcb-composite, version 1.14
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.14
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.14
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.14
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.3
-- Checking for module 'xcb-cursor'
--   Found xcb-cursor, version 0.1.3
--  Build:
--    Version: 3.4.0-99-g92181fd
--    Type: Release
--    CXX: /usr/bin/c++  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
--    LD: /usr/bin/ld
--  Install Paths:
--    PREFIX:  /usr/local
--    BINDIR:  /usr/local/bin
--    DATADIR: /usr/local/share
--    DOCDIR:  /usr/local/share/doc/polybar
--    MANDIR:  /usr/local/share/man
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
-- [X]   documentation
--  Module support:
-- [X]   alsa (1.2.2)
-- [X]   curl (7.70.0)
-- [X]   i3
-- [X]   mpd (2.18)
-- [X]   network (libnl) (3.5.0)
-- [X]   pulseaudio (13.0)
-- [X]   xkeyboard (1.14)
--  X extensions:
-- [X]   xcb-randr (1.14)
-- [X]   xcb-randr (monitor support) (1.14)
-- [X]   xcb-composite (1.14)
-- [X]   xcb-xkb (1.14)
-- [X]   xcb-xrm (1.3)
-- [X]   xcb-cursor (0.1.3)
--  Log options:
-- [X]   Trace logging
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.14
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.2", minimum required is "3.5")
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/libxcb.so
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/libxcb-icccm.so
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/libxcb-ewmh.so
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/libxcb-util.so
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/libxcb-image.so
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so
-- Searching for xcbgen with python3
-- Found xcbgen in /usr/lib/python3.8/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/libxcb-randr.so
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so
-- XCB[COMPOSITE]: Found component COMPOSITE
-- Found XCB_COMPOSITE: /usr/lib/libxcb-composite.so
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so;/usr/lib/libxcb-composite.so
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib/libxcb-xkb.so
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so;/usr/lib/libxcb-composite.so;/usr/lib/libxcb-xkb.so
-- xpp: including xcb proto composite.xml
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.9.2
-- Found font: misc fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sflip/src/polybar/build

> make -j(nproc)
Scanning dependencies of target doc_html
Scanning dependencies of target doc_man
[  1%] Generating generated-sources/include/xpp/proto/x.hpp
[  2%] sphinx-build html: see doc/builder-html.log
Scanning dependencies of target i3ipc++
[  3%] sphinx-build man: see doc/builder-man.log
[  4%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'alabaster<0.8,>=0.7' distribution was not found and is required by Sphinx
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'alabaster<0.8,>=0.7' distribution was not found and is required by Sphinx
make[2]: *** [doc/CMakeFiles/doc_man.dir/build.make:78: doc/CMakeFiles/doc_man] Error 1
make[1]: *** [CMakeFiles/Makefile2:460: doc/CMakeFiles/doc_man.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [doc/CMakeFiles/doc_html.dir/build.make:78: doc/CMakeFiles/doc_html] Error 1
make[1]: *** [CMakeFiles/Makefile2:487: doc/CMakeFiles/doc_html.dir/all] Error 2
[  5%] Generating generated-sources/include/xpp/proto/composite.hpp
[  6%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc-util.cpp.o
[  7%] Generating generated-sources/include/xpp/proto/randr.hpp
list: size, ['red', 'green', 'blue']
list: size, ['red', 'green', 'blue']
[  8%] Generating generated-sources/include/xpp/proto/xkb.hpp
[  9%] Linking CXX static library libi3ipc++.a
[  9%] Built target i3ipc++
Scanning dependencies of target xpp
[ 10%] Linking CXX static library libxpp.a
[ 10%] Built target xpp
make: *** [Makefile:150: all] Error 2
```

## Environment:
* Distro (with Version): Arch Linux

## Additional context
```
> uname -a
Linux dwarf 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux

> cmake --version
cmake version 3.17.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

> gcc --version
gcc (Arch Linux 9.3.0-1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

> python --version
Python 3.8.2

> pip show sphinx
Name: Sphinx
Version: 3.0.3
Summary: Python documentation generator
Home-page: http://sphinx-doc.org/
Author: Georg Brandl
Author-email: georg@python.org
License: BSD
Location: /usr/lib/python3.8/site-packages
Requires: sphinxcontrib-applehelp, sphinxcontrib-devhelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, Jinja2, Pygments, docutils, snowballstemmer, babel, alabaster, imagesize, requests, setuptools, packaging
Required-by:
```

**Comment by patrick96** [comment]
Do you use pyenv or conda or something similar to manage your python installation? Those like to interfere with system python packages.

If not, can you check that the `python-sphinx-alabaster-theme` is correctly installed?

**Comment by sflip** [comment]
Thanks for responding!

For the manual build task, no, I didn't use a virtual environment, but `python-sphinx-alabaster-theme` is installed on my system:
```
> yay -Qi python-sphinx-alabaster-theme
Name            : python-sphinx-alabaster-theme
Version         : 0.7.12-3
Description     : Sphinx default theme
Architecture    : any
URL             : https://github.com/bitprophet/alabaster
Licenses        : custom:BSD
Groups          : None
Provides        : None
Depends On      : None
Optional Deps   : None
Required By     : python-sphinx
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 40.32 KiB
Packager        : Evangelos Foutras <evangelos@foutrelis.com>
Build Date      : Thu 31 Oct 2019 06:37:31 PM CET
Install Date    : Fri 15 Nov 2019 10:28:49 AM CET
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

However I tried building with a virtual environment now, and it succeeded. Looks like my system python packages are somewhat broken.

I'm closing this issue now. Thank you @patrick96!

**Comment by patrick96** [comment]
Interesting. Normally people can't build **with** a virtual environment.
