### ISSUE TITLE
Compiling polybar throws an exception sphinxcontrib-jsmath not found in Python2.7

### ISSUE THREAD

**Issue by cfellicious** [polybar/polybar#2140]
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sphinxcontrib-jsmath' distribution was not found and is required by Sphinx
doc/CMakeFiles/doc_html.dir/build.make:57: recipe for target 'doc/CMakeFiles/doc_html' failed
make[2]: *** [doc/CMakeFiles/doc_html] Error 1
CMakeFiles/Makefile2:343: recipe for target 'doc/CMakeFiles/doc_html.dir/all' failed
make[1]: *** [doc/CMakeFiles/doc_html.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

The code picks up Python 2.7 instead of Python 3 which I already have installed

**Comment by patrick96** [comment]
which distro? Do you maybe have sphinx for python2 instead of python3?

**Comment by cfellicious** [comment]
> which distro? Do you maybe have sphinx for python2 instead of python3?

I am using Ubutu 18.04 LTS.
I had sphinx for python2 and uninstalled it. It still has the same error.

**Comment by patrick96** [comment]
Please post the entire build output (cmake and make). Also, how did you install sphinx? The ubuntu package doesn't install to `/usr/local`

**Comment by cfellicious** [comment]
CMake Warning at CMakeLists.txt:5 (find_package):
  By not providing "FindPython3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python3" with any
  of the following names:

    Python3Config.cmake
    python3-config.cmake

  Add the installation prefix of "Python3" to CMAKE_PREFIX_PATH or set
  "Python3_DIR" to a directory containing one of the above files.  If
  "Python3" provides a separate development package or SDK, be sure it has
  been installed.


-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using Release
-- Using supported compiler GNU-7.5.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.15.10
-- Checking for module 'alsa'
--   Found alsa, version 1.1.3
-- Checking for module 'libcurl'
--   Found libcurl, version 7.58.0
-- Checking for module 'libmpdclient'
--   Found libmpdclient, version 2.11
-- Found Libiw: /usr/lib/x86_64-linux-gnu/libiw.so  
-- Checking for module 'libpulse'
--   Found libpulse, version 11.1
-- Checking for module 'xcb-composite'
--   Found xcb-composite, version 1.13
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.13
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.13
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.13
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.0
--  Build:
--    Version: 3.4.0-113-ga625e2b-dev
--    Type: Release
--    CXX: /usr/bin/c++  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
--    LD: /usr/bin/ld  
--  Install Paths:
--    PREFIX:  /usr/local
--    BINDIR:  /usr/local/bin
--    DATADIR: /usr/local/share
--    DOCDIR:  /usr/local/share/doc/polybar
--    MANDIR:  /usr/local/share/man
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
-- [X]   documentation
--  Module support:
-- [X]   alsa (1.1.3)
-- [X]   curl (7.58.0)
-- [X]   i3
-- [X]   mpd (2.11)
-- [X]   network (wireless-tools)
-- [X]   pulseaudio (11.1)
-- [X]   xkeyboard (1.13)
--  X extensions:
-- [X]   xcb-randr (1.13)
-- [X]   xcb-randr (monitor support) (1.13)
-- [X]   xcb-composite (1.13)
-- [X]   xcb-xkb (1.13)
-- [X]   xcb-xrm (1.0)
-- [ ]   xcb-cursor
--  Log options:
-- [X]   Trace logging
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.13
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3.5") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/x86_64-linux-gnu/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/x86_64-linux-gnu/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/x86_64-linux-gnu/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Searching for xcbgen with /usr/bin/python3
-- Searching for xcbgen with python3
-- Searching for xcbgen with python
-- Found xcbgen in /usr/lib/python2.7/dist-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- XCB[COMPOSITE]: Found component COMPOSITE
-- Found XCB_COMPOSITE: /usr/lib/x86_64-linux-gnu/libxcb-composite.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so;/usr/lib/x86_64-linux-gnu/libxcb-composite.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so;/usr/lib/x86_64-linux-gnu/libxcb-composite.so;/usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- xpp: including xcb proto composite.xml
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aaaaaa/PycharmProjects/polybar/build

Output of make
Scanning dependencies of target doc_html
[  1%] sphinx-build html: see doc/builder-html.log
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sphinxcontrib-jsmath' distribution was not found and is required by Sphinx
doc/CMakeFiles/doc_html.dir/build.make:57: recipe for target 'doc/CMakeFiles/doc_html' failed
make[2]: *** [doc/CMakeFiles/doc_html] Error 1
CMakeFiles/Makefile2:343: recipe for target 'doc/CMakeFiles/doc_html.dir/all' failed
make[1]: *** [doc/CMakeFiles/doc_html.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cfellicious** [comment]
I also tried running the build.sh script. This is the output of that.
./build.sh 
** Fetching submodules

** A build dir already exists (pass -f to replace)

** Setting build options

** Use GCC even if Clang is installed ----------------------------- [y/N]: y
** Include support for "internal/i3" (requires i3) ---------------- [y/N]: y
** Include support for "internal/alsa" (requires alsalib) --------- [y/N]: y
** Include support for "internal/pulseaudio" (requires libpulse) -- [y/N]: y
** Include support for "internal/network" (requires libnl/libiw) -- [y/N]: y
** Include support for "internal/mpd" (requires libmpdclient) ----- [y/N]: y
** Include support for "internal/github" (requires libcurl) ------- [y/N]: y
** Build "polybar-msg" used to send ipc messages ------------------ [y/N]: y
** Parallelize the build using make -j8 --------------------------- [y/N]: y
** Executing cmake command

CMake Warning at CMakeLists.txt:5 (find_package):
  By not providing "FindPython3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python3" with any
  of the following names:

    Python3Config.cmake
    python3-config.cmake

  Add the installation prefix of "Python3" to CMAKE_PREFIX_PATH or set
  "Python3_DIR" to a directory containing one of the above files.  If
  "Python3" provides a separate development package or SDK, be sure it has
  been installed.


-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
y-- Detecting CXX compile features - done
-- No build type specified; using Release
-- Using supported compiler GNU-7.5.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.15.10
-- Checking for module 'alsa'
--   Found alsa, version 1.1.3
-- Checking for module 'libcurl'
--   Found libcurl, version 7.58.0
-- Checking for module 'libmpdclient'
--   Found libmpdclient, version 2.11
-- Found Libiw: /usr/lib/x86_64-linux-gnu/libiw.so  
-- Checking for module 'libpulse'
--   Found libpulse, version 11.1
-- Checking for module 'xcb-composite'
--   Found xcb-composite, version 1.13
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.13
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.13
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.13
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.0
--  Build:
--    Version: 3.4.0-113-ga625e2b-dev
--    Type: Release
--    CXX: /usr/bin/g++  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
--    LD: /usr/bin/ld  
--  Install Paths:
--    PREFIX:  /usr/local
--    BINDIR:  /usr/local/bin
--    DATADIR: /usr/local/share
--    DOCDIR:  /usr/local/share/doc/polybar
--    MANDIR:  /usr/local/share/man
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
-- [X]   documentation
--  Module support:
-- [X]   alsa (1.1.3)
-- [X]   curl (7.58.0)
-- [X]   i3
-- [X]   mpd (2.11)
-- [X]   network (wireless-tools)
-- [X]   pulseaudio (11.1)
-- [X]   xkeyboard (1.13)
--  X extensions:
-- [X]   xcb-randr (1.13)
-- [X]   xcb-randr (monitor support) (1.13)
-- [X]   xcb-composite (1.13)
-- [X]   xcb-xkb (1.13)
-- [X]   xcb-xrm (1.0)
-- [ ]   xcb-cursor
--  Log options:
-- [X]   Trace logging
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.13
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3.5") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/x86_64-linux-gnu/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/x86_64-linux-gnu/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/x86_64-linux-gnu/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Searching for xcbgen with /usr/bin/python3
-- Searching for xcbgen with python3
-- Searching for xcbgen with python
-- Found xcbgen in /usr/lib/python2.7/dist-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- XCB[COMPOSITE]: Found component COMPOSITE
-- Found XCB_COMPOSITE: /usr/lib/x86_64-linux-gnu/libxcb-composite.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so;/usr/lib/x86_64-linux-gnu/libxcb-composite.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so;/usr/lib/x86_64-linux-gnu/libxcb-composite.so;/usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- xpp: including xcb proto composite.xml
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aaaaaa/PycharmProjects/polybar/build
** Building project

[  3%] Generating generated-sources/include/xpp/proto/randr.hpp
[  3%] Generating generated-sources/include/xpp/proto/xkb.hpp
[  3%] Generating generated-sources/include/xpp/proto/x.hpp
[  4%] Generating generated-sources/include/xpp/proto/composite.hpp
Scanning dependencies of target doc_man
Scanning dependencies of target i3ipc++
Scanning dependencies of target doc_html
Scanning dependencies of target polybar-msg
[  6%] sphinx-build man: see doc/builder-man.log
[  6%] sphinx-build html: see doc/builder-html.log
[  7%] Building CXX object bin/CMakeFiles/polybar-msg.dir/ipc.cpp.o
[  8%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sphinxcontrib-jsmath' distribution was not found and is required by Sphinx
[  9%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc-util.cpp.o
doc/CMakeFiles/doc_man.dir/build.make:57: recipe for target 'doc/CMakeFiles/doc_man' failed
make[2]: *** [doc/CMakeFiles/doc_man] Error 1
CMakeFiles/Makefile2:311: recipe for target 'doc/CMakeFiles/doc_man.dir/all' failed
make[1]: *** [doc/CMakeFiles/doc_man.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/aaaaaa/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sphinxcontrib-jsmath' distribution was not found and is required by Sphinx
[ 10%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/env.cpp.o
doc/CMakeFiles/doc_html.dir/build.make:57: recipe for target 'doc/CMakeFiles/doc_html' failed
make[2]: *** [doc/CMakeFiles/doc_html] Error 1
CMakeFiles/Makefile2:343: recipe for target 'doc/CMakeFiles/doc_html.dir/all' failed
make[1]: *** [doc/CMakeFiles/doc_html.dir/all] Error 2
[ 11%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/file.cpp.o
list: size, ['red', 'green', 'blue']
list: size, ['red', 'green', 'blue']
[ 12%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/string.cpp.o
[ 13%] Linking CXX executable polybar-msg
[ 13%] Built target polybar-msg
[ 14%] Linking CXX static library libi3ipc++.a
[ 14%] Built target i3ipc++
Scanning dependencies of target xpp
[ 15%] Linking CXX static library libxpp.a
[ 15%] Built target xpp
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
** Failed to build project

**Comment by patrick96** [comment]
This is most definitely a problem with your sphinx installation, what happens if you just run `sphinx-build` in your terminal?

How did you install `sphinx-build`? In particular to which package does `/usr/local/bin/sphinx-build` belong?

Are you in a pyenv here or use some other non-system python distribution?

**Comment by patrick96** [comment]
Closing due to inactivity
