### ISSUE TITLE
Make can't find xcbgen, existing discussions didn't help

### ISSUE THREAD

**Issue by RawEnchilada** [polybar/polybar#2259]
## Checklist

* [x] I have followed every step on the [compiling wiki page](https://github.com/polybar/polybar/wiki/Compiling) and
  installed all necessary dependencies.
* [ ] My problem is not described on the [known issues page](https://github.com/polybar/polybar/wiki/Known-Issues)
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I was able to reproduce this build issue in a clean build

## Build Process

**How did you build polybar?**

* [ ] From a release archive (Which version?)
* [x] By cloning this repository (What is the of `git describe --tags`?)
* [ ] Some other way (How?)

```
git clone --recursive https://github.com/polybar/polybar
cd polybar
mkdir build
cd build
cmake .. -DPYTHON_XCBGEN=/usr/lib/python2.7/dist-packages/

# i am setting xcbgen manually as suggested here: 
# https://github.com/polybar/polybar/issues/2031
# without this cmake cant find xcbgen either even though it exists in python3.9  folder

make -j$(nproc) # build failed
```

i have also tried with 
```
yay -S polybar
```
yay can't find xcbgen either

## Build Log
```
[  1%] Generating generated-sources/include/xpp/proto/xkb.hpp
[  2%] Generating generated-sources/include/xpp/proto/randr.hpp
Scanning dependencies of target doc_man
Scanning dependencies of target doc_html
[  3%] Generating generated-sources/include/xpp/proto/composite.hpp
Scanning dependencies of target polybar-msg
[  4%] Generating generated-sources/include/xpp/proto/x.hpp
[  5%] sphinx-build man: see doc/builder-man.log
[  6%] sphinx-build html: see doc/builder-html.log
[  8%] Building CXX object bin/CMakeFiles/polybar-msg.dir/ipc.cpp.o
[  8%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/env.cpp.o
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 33, in <module>
    sys.exit(load_entry_point('Sphinx==3.3.1', 'console_scripts', 'sphinx-build')())
  File "/usr/bin/sphinx-build", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Sphinx
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 33, in <module>
    sys.exit(load_entry_point('Sphinx==3.3.1', 'console_scripts', 'sphinx-build')())
  File "/usr/bin/sphinx-build", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Sphinx
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/enchilada/polybar/lib/xpp/generators/cpp_client.py", line 3096, in <module>
  File "/home/enchilada/polybar/lib/xpp/generators/cpp_client.py", line 3096, in <module>
Traceback (most recent call last):
  File "/home/enchilada/polybar/lib/xpp/generators/cpp_client.py", line 3096, in <module>
    from xcbgen.state import Module
ModuleNotFoundError: No module named 'xcbgen'
    from xcbgen.state import Module
ModuleNotFoundError: No module named 'xcbgen'
    from xcbgen.state import Module
ModuleNotFoundError: No module named 'xcbgen'
make[2]: *** [doc/CMakeFiles/doc_man.dir/build.make:77: doc/CMakeFiles/doc_man] Error 1
  File "/home/enchilada/polybar/lib/xpp/generators/cpp_client.py", line 3096, in <module>
make[1]: *** [CMakeFiles/Makefile2:466: doc/CMakeFiles/doc_man.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
    from xcbgen.state import Module
ModuleNotFoundError: No module named 'xcbgen'
make[2]: *** [doc/CMakeFiles/doc_html.dir/build.make:77: doc/CMakeFiles/doc_html] Error 1
make[1]: *** [CMakeFiles/Makefile2:493: doc/CMakeFiles/doc_html.dir/all] Error 2
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:81: lib/xpp/generated-sources/include/xpp/proto/composite.hpp] Error 1
make[2]: *** Deleting file 'lib/xpp/generated-sources/include/xpp/proto/composite.hpp'
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:93: lib/xpp/generated-sources/include/xpp/proto/x.hpp] Error 1
make[2]: *** Deleting file 'lib/xpp/generated-sources/include/xpp/proto/x.hpp'
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:89: lib/xpp/generated-sources/include/xpp/proto/xkb.hpp] Error 1
make[2]: *** Deleting file 'lib/xpp/generated-sources/include/xpp/proto/xkb.hpp'
[  9%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/file.cpp.o
[ 10%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/string.cpp.o
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:85: lib/xpp/generated-sources/include/xpp/proto/randr.hpp] Error 1
make[2]: *** Deleting file 'lib/xpp/generated-sources/include/xpp/proto/randr.hpp'
make[1]: *** [CMakeFiles/Makefile2:519: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
[ 11%] Linking CXX executable polybar-msg
[ 11%] Built target polybar-msg
make: *** [Makefile:149: all] Error 2
```

## Environment:
ArchLinux version 5.9.11-arch2-1

## Additional context
So i've searched every open issue and discussion about this, since there is a lot., none of them were able to solve my issue.
I'm not using anaconda nor pyenv
I've tried to build manually and with aur helpers
i've tried installing python2 packages
xcbgen exists in usr/lib/python3.9/site-packages
I've even tried installing xcbgen via apt, which i know i shouldn't do on arch

**Comment by patrick96** [comment]
First of, the following should always work on Arch:

```bash
# Clone the AUR repository (https://aur.archlinux.org/polybar-git.git for the polybar-git package should work as well):
git clone https://aur.archlinux.org/polybar.git
cd polybar # or polybar-git
extra-x86_64-build # Builds polybar in a clean chroot.
```

This builds the polybar package on a clean system. If that works but it doesn't directly on your system, the issue likely is with your system setup. Most often those "issues" would be pyenv or conda that shadow the system python executables, but since you don't use those, there must be another issue.

---

Now, I see a few issues with your machine, any one of them could be responsible for this issue:

* Your system has the file `/usr/lib/python3.8/importlib/metadata.py`, this suggests you are using python 3.8, but since the xcbgen files are in `/usr/lib/python3.9/site-packages`, your system is also using python 3.9. Since you're on arch, you should really only have python3.9 files (at least in `/usr/lib`).
* "I've even tried installing xcbgen via apt, which i know i shouldn't do on arch":  
This is not a good idea *at all*. Installing any apt package is bound to break your system one way or another.

There is definitely something borked in your system, my best guess is that it is because both the `python` and `python3` executables are actually for 3.8 and not 3.9, this would explain why polybar couldn't find xcbgen during cmake.

>  i've tried installing python2 packages

You should really only need python2 for building polybar if your distro doesn't have xcbgen for your python3 version.

**Comment by RawEnchilada** [comment]
You were right, thank you!

I uninstalled every python package with 
sudo pacman -Rcns python
Then yay was able to build it successfully
