### ISSUE TITLE
Sphinx Error while building

### ISSUE THREAD

**Issue by handlederror** [polybar/polybar#2302]
I get this error while installing the polybar from AUR with yay:

```python
Scanning dependencies of target doc_html
[  0%] sphinx-build html: see doc/builder-html.log
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 33, in <module>
    sys.exit(load_entry_point('Sphinx==3.3.1', 'console_scripts', 'sphinx-build')())
  File "/usr/bin/sphinx-build", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 26, in <module>
    from docutils.parsers.rst import Directive, roles
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/__init__.py", line 75, in <module>
    from docutils.parsers.rst import roles, states
  File "/usr/lib/python3.9/site-packages/docutils/parsers/rst/roles.py", line 78, in <module>
    from docutils.utils.code_analyzer import Lexer, LexerError
  File "/usr/lib/python3.9/site-packages/docutils/utils/code_analyzer.py", line 12, in <module>
    from pkg_resources import DistributionNotFound as ResourceError
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'packaging' distribution was not found and is required by Sphinx
make[2]: *** [doc/CMakeFiles/doc_html.dir/build.make:77: doc/CMakeFiles/doc_html] Error 1
make[1]: *** [CMakeFiles/Makefile2:514: doc/CMakeFiles/doc_html.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by TheWithz** [comment]
I had this problem in gentoo. Part of the problem was a version conflict between python and pip. pip version was 3.8.1 but python was still on 3.7
this meant that installing packages with pip didn't affect the build
I also ended up reinstalling sphinx from the package manager and both of those together fixed the issue for me

**Comment by handlederror** [comment]
I did installed sphinx with pip and it worked. ( And removed the `python-sphinx` package using `doas pacman -R python-sphinx`. )
