### ISSUE TITLE
Segmentation fault using xworkspaces module

### ISSUE THREAD

**Issue by Mwakamune** [polybar/polybar#2352]
I just installed Ubuntu 20.04 on my XPS13 with openbox and polybar get a segfault when i use xworkspaces module. I also have an old ASUS zenbook with the same config and it works well. 

I use the example file where i add the module "xworkspaces"

```
[module/xworkspaces]
type = internal/xworkspaces

; Only show workspaces defined on the same output as the bar
;
; Useful if you want to show monitor specific workspaces
; on different bars
;
; Default: false
pin-workspaces = true

; Create click handler used to focus desktop
; Default: true
enable-click = false

; Create scroll handlers used to cycle desktops
; Default: true
enable-scroll = false

```
I only display this module 
```

modules-left =
modules-center = xworkspaces
modules-right =
```

The output of  `gdb -ex run -args polybar example --log=trace` is as follows:

```
$ gdb -ex run -args polybar example --log=trace                                                                                                                                                                                                130 ↵  [18:10:29]
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from polybar...
(No debugging symbols found in polybar)
Starting program: /usr/local/bin/polybar example --log=trace
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
notice: Parsing config file: /home/keijy/.config/polybar/config
- config_parser: Parsing /home/keijy/.config/polybar/config
- config: Inheriting keys from "module/xbacklight" in "module/backlight-acpi"
* Created ipc channel at: /tmp/polybar_mqueue.7623
[New Thread 0x7ffff512d700 (LWP 7627)]
warn: No monitor specified, using "DP-1"
* Loaded monitor DP-1 (2560x1440+0+0)
* Bar geometry: 2560x35+0+0; Borders: 4,4,4,4
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Install signal handler
- controller: Setup user-defined modules
* Starting application
- controller: Main thread id = 1
* Starting module/xworkspaces
[New Thread 0x7ffff492c700 (LWP 7628)]
- module/xworkspaces: Thread id = 2
[New Thread 0x7fffeffff700 (LWP 7629)]
[Thread 0x7ffff492c700 (LWP 7628) exited]
* Eventqueue worker (thread-id=3)
* Entering event loop (thread-id=1)
- bar: Create renderer
- renderer: Get TrueColor visual
- renderer: Allocate colormap
- renderer: Allocate output window
- renderer: Allocate window pixmaps
- renderer: Allocate graphic contexts
- renderer: Allocate alignment blocks
- renderer: Allocate cairo components
- renderer: Load fonts
* Configured DPI = 96x96
notice: Loaded font "fixed:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
notice: Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
notice: Loaded font "siji:pixelsize=10" (name=siji, offset=1, file=/home/keijy/.local/share/fonts/siji.ttf)
* Bar window: 0x2e00002
- bar: Reconfigure window
- bar: Set window WM_NAME
- bar: Set window _NET_WM_WINDOW_TYPE
- bar: Set window _NET_WM_STATE
- bar: Set window _NET_WM_DESKTOP
- bar: Set window _NET_WM_PID
- bar: Map window
- bar: Draw empty bar
- bar: Setup tray manager
- tray: Find systray selection atom for the default screen
* Activating tray manager
- tray: Create tray window
* Tray window: 0x2e00009
- tray: Restacking tray window
error: tray: Failed to put tray above 0x2e00002 in the stack (XCB_MATCH (8))
- bar: Set window WM_NAME / WM_CLASS
- tray: Set window WM_PROTOCOLS
- tray: Set window _NET_WM_WINDOW_TYPE
- tray: Set window _NET_WM_STATE
- tray: Set window _NET_WM_PID
- tray: Set window _NET_SYSTEM_TRAY_VISUAL
- tray: Set window _NET_SYSTEM_TRAY_ORIENTATION
- tray: Set _NET_SYSTEM_TRAY_COLORS to ff222222
- tray: Change selection owner to 0x2e00009
[New Thread 0x7fffef745700 (LWP 7630)]
- tray: visibility_change (state=0, activated=1, mapped=0, hidden=0)
* module/xworkspaces: Rebuilding cache

Thread 1 "polybar" received signal SIGSEGV, Segmentation fault.
0x00005555556aafe7 in polybar::modules::xworkspaces_module::rebuild_urgent_hints() ()
```

and `thread apply all bt full` after that :

```
(gdb) thread apply all bt full

Thread 5 (Thread 0x7fffef745700 (LWP 7630)):
#0  0x00007ffff72203bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffef7449e0, rem=0x7fffef7449e0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
        r = <optimized out>
#1  0x00007ffff7226047 in __GI___nanosleep (requested_time=<optimized out>, remaining=<optimized out>) at nanosleep.c:27
        ret = <optimized out>
#2  0x00005555556e3ee5 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<polybar::tray_manager::notify_clients_delayed()::{lambda()#1}> > >::_M_run() ()
No symbol table info available.
#3  0x00007ffff7595d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff733b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737210767104, 7910430212107794361, 140737219912830, 140737219912831, 140737219912832, 140737210764032, -7910396044990220359, -7910414163634948167}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#5  0x00007ffff7262293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7fffeffff700 (LWP 7629)):
#0  __lll_lock_wait (futex=futex@entry=0x5555558389a8, private=0) at lowlevellock.c:52
        __ret = <optimized out>
#1  0x00007ffff733e0a3 in __GI___pthread_mutex_lock (mutex=0x5555558389a8) at ../nptl/pthread_mutex_lock.c:80
        __futex = 0x5555558389a8
        type = <optimized out>
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        id = <optimized out>
#2  0x00005555556a965c in polybar::modules::xworkspaces_module::get_output[abi:cxx11]() ()
No symbol table info available.
#3  0x00005555556b17f8 in polybar::modules::module<polybar::modules::xworkspaces_module>::contents[abi:cxx11]() ()
No symbol table info available.
#4  0x00005555555fe30f in polybar::controller::process_update(bool) ()
No symbol table info available.
#5  0x000055555560a3dc in polybar::controller::process_eventqueue() ()
No symbol table info available.
#6  0x00007ffff7595d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x00007ffff733b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737219917568, 7910430212107794361, 140737488342558, 140737488342559, 140737488342560, 140737219914496, -7910395028156713031, -7910414163634948167}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#8  0x00007ffff7262293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7ffff512d700 (LWP 7627)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55555581ea58) at ../sysdeps/nptl/futex-internal.h:183
        __ret = -512
        oldtype = 0
        err = <optimized out>
        oldtype = <optimized out>
        err = <optimized out>
        __ret = <optimized out>
        resultvar = <optimized out>
        __arg4 = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a4 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555581ea08, cond=0x55555581ea30) at pthread_cond_wait.c:508
        spin = 0
        buffer = {__routine = 0x7ffff7342050 <__condvar_cleanup_waiting>, __arg = 0x7ffff512c930, __canceltype = 0, __prev = 0x0}
        cbuffer = {wseq = 0, cond = 0x55555581ea30, mutex = 0x55555581ea08, private = 0}
        err = <optimized out>
        g = 0
        flags = <optimized out>
        g1_start = <optimized out>
        signals = <optimized out>
        result = 0
--Type <RET> for more, q to quit, c to continue without paging--c
        wseq = 0
        seq = 0
        private = <optimized out>
        maxspin = <optimized out>
        err = <optimized out>
        result = <optimized out>
        wseq = <optimized out>
        g = <optimized out>
        seq = <optimized out>
        flags = <optimized out>
        private = <optimized out>
        signals = <optimized out>
        g1_start = <optimized out>
        spin = <optimized out>
        buffer = <optimized out>
        cbuffer = <optimized out>
        s = <optimized out>
#2  __pthread_cond_wait (cond=0x55555581ea30, mutex=0x55555581ea08) at pthread_cond_wait.c:638
No locals.
#3  0x00007ffff758fe50 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x000055555562c340 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<polybar::taskqueue::taskqueue()::{lambda()#1}> > >::_M_run() ()
No symbol table info available.
#5  0x00007ffff7595d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff733b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737305040640, 7910430212107794361, 140737488342366, 140737488342367, 140737488342368, 140737305037568, -7910409501122758727, -7910414163634948167}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007ffff7262293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7ffff51310c0 (LWP 7623)):
#0  0x00005555556aafe7 in polybar::modules::xworkspaces_module::rebuild_urgent_hints() ()
No symbol table info available.
#1  0x00005555556ac08c in polybar::modules::xworkspaces_module::rebuild_clientlist() ()
No symbol table info available.
#2  0x00005555556ac36c in polybar::modules::xworkspaces_module::handle(xpp::x::event::property_notify<polybar::connection&> const&) ()
No symbol table info available.
#3  0x00005555556d9497 in bool xpp::x::event::dispatcher<polybar::connection&>::operator()<xpp::event::registry<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>::handler>(xpp::event::registry<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>::handler, std::shared_ptr<xcb_generic_event_t> const&) const ()
No symbol table info available.
#4  0x00005555556d48ad in polybar::connection::dispatch_event(std::shared_ptr<xcb_generic_event_t> const&) const ()
No symbol table info available.
#5  0x00005555555ff2ed in polybar::controller::read_events() ()
No symbol table info available.
#6  0x000055555560bfea in polybar::controller::run(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
No symbol table info available.
#7  0x00005555555b79a3 in main ()
No symbol table info available.
```

**Comment by patrick96** [comment]
Thanks for reporting. I was able to reproduce it on openbox as well. I'll have a fix ready soon

**Comment by Mwakamune** [comment]
thx a lot <3
