### ISSUE TITLE
segmentation fault when `pin-workspaces = false` in xworkspaces module 

### ISSUE THREAD

**Issue by amrbashir** [polybar/polybar#2398]
## Checklist

* [X] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
removing or setting `pin-workspaces = false` results in `segmentation fault`

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
* If no, what was the last version where this worked correctly?
not to my knowledge

## To Reproduce

```dosini
[module/workspaces]
type = internal/xworkspaces

pin-workspaces = false

[bar/main]
modules-left = workspaces
```

## Polybar Log

```
[1]    319850 segmentation fault (core dumped)  polybar -q main -c ~/dotfiles/linux/polybar/docky/config.ini
```

## Environment:
* WM: AwesomeWM
* Distro: Arch
* Output of `polybar -vvv`:

```
polybar 3.5.5

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context

`xprop -root` after the crash 
```
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x1200007
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x4000001
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x4000001
_NET_CLIENT_LIST(WINDOW): window id # 0x1200007, 0x1000005
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x1000005, 0x1200007
PULSE_COOKIE(STRING) = "5ff9019729bcb7d17a8e9f46f64b015d858f7b8c64128b0edeeec97b83ad2da7f9fd487313b776bffedb17f51c9ce0ce575893f3846628fcf325305e4a56b98f05c0b9478ddba64314e9e59d5026fe815b95a55f0ee514df3599d6c13c5581d62c8e7a9557152c0e2b4d0a9a4c868e3f1ccdadcf3da4553c640b294b0076a3998b51c6367fc99c9920f4794419c53f1806bb30079618494648491ce6de3b829d5d38d8128cdf74eebe2c04417c1de8fa63f00c769660ca3b193f728eb585d0763bd6338a499b5bc2aaaabf1eed3b975f7410ac0a395444819faa322f76f494a72c081fdb1b844b6a2c7036ff788b6b2df1d182246afdd4d1c22a7c573a351635"
PULSE_SERVER(STRING) = "{5d23e2a19cb8467997830c10f0665354}unix:/run/user/1000/pulse/native"
PULSE_ID(STRING) = "1000@5d23e2a19cb8467997830c10f0665354/313358"
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x400005
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_SUPPORTING_WM_CHECK, _NET_STARTUP_ID, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_NUMBER_OF_DESKTOPS, _NET_CURRENT_DESKTOP, _NET_DESKTOP_NAMES, _NET_ACTIVE_WINDOW, _NET_CLOSE_WINDOW, _NET_FRAME_EXTENTS, _NET_WM_NAME, _NET_WM_STRUT_PARTIAL, _NET_WM_ICON_NAME, _NET_WM_VISIBLE_ICON_NAME, _NET_WM_DESKTOP, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU, _NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_COMBO, _NET_WM_WINDOW_TYPE_DND, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_ICON, _NET_WM_PID, _NET_WM_STATE, _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_MODAL, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_DEMANDS_ATTENTION
RESOURCE_MANAGER(STRING) = 
XFree86_DDC_EDID1_RAWDATA(INTEGER) = 0, -1, -1, -1, -1, -1, -1, 0, 13, -82, -62, 21, 0, 0, 0, 0, 4, 23, 1, 4, -107, 34, 19, 120, 2, 70, 53, -98, 87, 87, -108, 39, 20, 80, 84, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -76, 59, -128, 74, 113, 56, 52, 64, 90, 60, 105, 0, 88, -62, 16, 0, 0, 26, -51, 39, -128, 74, 113, 56, 52, 64, 90, 60, 105, 0, 88, -62, 16, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 12, 51, -1, 15, 60, -106, 33, 20, 51, -106, 0, 0, 0, 0, 112
GDK_VISUALS(INTEGER) = 937, 1004
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 7
Xorg_Seat(STRING) = "seat0"

```
[polybar-coredump.zip](https://github.com/polybar/polybar/files/6073094/polybar-coredump.zip)

**Comment by patrick96** [comment]
Thanks for the detailed report.

From your log output and the coredump, it looks like the crash doesn't have to do anything with the xworkspaces module. Though you did report in gitter that with `pin-workspaces = true`, the module gives an error, which is weird.

Can you run polybar with trace logging (`-l trace`) and post the terminal output of that. I want to figure out how far polybar gets in its execution.

Also the `xprop` output seems weird to me. i3 reports that it supports the `_NET_NUMBER_OF_DESKTOPS` atom, but it doesn't actually appear anywhere. Can you also run the following command: `xprop -root _NET_NUMBER_OF_DESKTOPS`.

If you are able to, compiling polybar in debug mode (`cmake -DCMAKE_BUILD_TYPE=Debug ..`) and posting the coredump (or a full backtrace in gdb) would be extremely helpful.

**Comment by amrbashir** [comment]
here is the `-l trace`
```
❯ polybar main -c ~/dotfiles/linux/polybar/docky/config.ini -l trace
notice: Parsing config file: /home/amr/dotfiles/linux/polybar/docky/config.ini
- config_parser: Parsing /home/amr/dotfiles/linux/polybar/docky/config.ini
- config_parser: Parsing /home/amr/.config/polybar/docky/colors.ini
- config_parser: Parsing /home/amr/.config/polybar/docky/modules.ini
* Created ipc channel at: /tmp/polybar_mqueue.28457
* Loaded monitor eDP1 (1920x1080+0+0)
* Bar geometry: 1901x36+10+11; Borders: 0,0,2,0
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Install signal handler
- controller: Setup user-defined modules
[1]    28457 segmentation fault (core dumped)  polybar main -c ~/dotfiles/linux/polybar/docky/config.ini -l trace

```
and `xprop -root _NET_NUMBER_OF_DESKTOPS`
```
❯ xprop -root _NET_NUMBER_OF_DESKTOPS                                  
_NET_NUMBER_OF_DESKTOPS:  not found.
```

**Comment by amrbashir** [comment]
here is the coredump in debug mode
[polybar-coredump-debugmode.zip](https://github.com/polybar/polybar/files/6076750/polybar-coredump-debugmode.zip)

**Comment by patrick96** [comment]
Hmm, the coredump doesn't have any debug symbols either. Did you run the polybar executable that you compiled in debug mode?

You can get a full gdb backtrace like this:

* Run polybar in gdb: `gdb --args ...` where `...` is whatever command you use to run polybar
* This loads the gdb shell, once loaded, run `run`
* This should run and then break because of the segfault and put you back into the gdb shell. At that point run `thread apply all bt full` and this will print a complete stacktrace.

Does the crash also happen with the config file you gave in the initial post? Because your log output suggests that you are running a different config.

**Comment by amrbashir** [comment]
I pulled the aur package and changed the cmake command inside PKGBUILD, built it with Paru(aur helper) and CMake build step said it is building in debug mode. I installed my version of polybar before doing this too.
 
I will try it again later. And I will try to load a minimal config file to see if it crashes and try gdb too.

**Comment by patrick96** [comment]
> I pulled the aur package and changed the cmake command inside PKGBUILD, built it with Paru(aur helper) and CMake build step said it is building in debug mode. I installed my version of polybar before doing this too.

This doesn't work unfortunately. Either `makepkg` or `pacman` itself remove debug symbols from all executables in a package.

**Comment by amrbashir** [comment]
just followed the compile instructions

`-l trace` output
```
- config_parser: Parsing ./demo-config.ini
* Loaded monitor eDP1 (1920x1080+0+0)
* Bar geometry: 1920x24+0+0; Borders: 0,0,0,0
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Install signal handler
- controller: Setup user-defined modules
[1]    12361 segmentation fault (core dumped)  polybar main -c ./demo-config.ini -l trace
```

[polybar-coredum-debug.zip](https://github.com/polybar/polybar/files/6078605/polybar-coredum-debug.zip)


gdb full backtrace
```
❯ gdb --args polybar main -c ./demo-config.ini -l trace
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from polybar...
(gdb) run
Starting program: /usr/local/bin/polybar main -c ./demo-config.ini -l trace
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
notice: Parsing config file: ./demo-config.ini
- config_parser: Parsing ./demo-config.ini
[New Thread 0x7ffff629c640 (LWP 13074)]
* Loaded monitor eDP1 (1920x1080+0+0)
* Bar geometry: 1920x24+0+0; Borders: 0,0,0,0
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Install signal handler
- controller: Setup user-defined modules

Thread 1 "polybar" received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (
    this=this@entry=0x555555937240, __str=<error reading variable: Cannot access memory at address 0x8>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:259
259	/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc: No such file or directory.
(gdb) thread apply all bt full

Thread 2 (Thread 0x7ffff629c640 (LWP 13074) "polybar"):
#0  0x00007ffff77609ba in __futex_abstimed_wait_common64 () from /usr/lib/libpthread.so.0
No symbol table info available.
#1  0x00007ffff775a260 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
No symbol table info available.
#2  0x00007ffff7994bb1 in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:865
No locals.
#3  std::condition_variable::wait (this=<optimized out>, __lock=...) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
        __e = <optimized out>
#4  0x000055555562a866 in operator() (__closure=0x55555592dca8) at /home/amr/polybar/src/components/taskqueue.cpp:18
        guard = {_M_device = 0x5555559298d8, _M_owns = true}
        this = 0x5555559298d0
#5  0x000055555562c36c in std::__invoke_impl<void, polybar::taskqueue::taskqueue()::<lambda()> >(std::__invoke_other, struct {...} &&) (__f=...) at /usr/include/c++/10.2.0/bits/invoke.h:60
No locals.
#6  0x000055555562c321 in std::__invoke<polybar::taskqueue::taskqueue()::<lambda()> >(struct {...} &&) (__fn=...) at /usr/include/c++/10.2.0/bits/invoke.h:95
No locals.
#7  0x000055555562c2ce in std::thread::_Invoker<std::tuple<polybar::taskqueue::taskqueue()::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x55555592dca8) at /usr/include/c++/10.2.0/thread:264
No locals.
#8  0x000055555562c2a2 in std::thread::_Invoker<std::tuple<polybar::taskqueue::taskqueue()::<lambda()> > >::operator()(void) (this=0x55555592dca8) at /usr/include/c++/10.2.0/thread:271
No locals.
#9  0x000055555562c286 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<polybar::taskqueue::taskqueue()::<lambda()> > > >::_M_run(void) (this=0x55555592dca0) at /usr/include/c++/10.2.0/thread:215
No locals.
#10 0x00007ffff799abc4 in std::execute_native_thread_routine (__p=0x55555592dca0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
        __t = std::unique_ptr<std::thread::_State> = {get() = <optimized out>}
#11 0x00007ffff7754299 in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#12 0x00007ffff767d053 in clone () from /usr/lib/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7ffff629fe00 (LWP 13070) "polybar"):
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=this@entry=0x555555937240, __str=<error reading variable: Cannot access memory at address 0x8>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:259
        __rsize = <optimized out>
        __capacity = <optimized out>
#1  0x00007ffff7a093af in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__str=..., this=0x555555937240) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:1335
        __len = <optimized out>
        __alloc = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}
        __ptr = <optimized out>
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (this=0x555555937240, __str=...) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:667
No locals.
#3  0x00005555556d9653 in polybar::modules::xworkspaces_module::xworkspaces_module (this=0x555555936e50, bar=..., name_="", __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at /home/amr/polybar/src/modules/xworkspaces.cpp:99
        workspace = <optimized out>
        __for_range = <optimized out>
        __for_begin = Python Exception <class 'gdb.error'> value has been optimized out: 

--Type <RET> for more, q to quit, c to continue without paging--
        __for_end = Python Exception <class 'gdb.error'> value has been optimized out: 

        vec = Python Exception <class 'gdb.error'> value has been optimized out: 

#4  0x00005555555e8403 in polybar::(anonymous namespace)::make_module (name=..., bar=..., module_name="", m_log=...) at /home/amr/polybar/include/modules/meta/factory.hpp:97
No locals.
#5  0x00005555555f060a in polybar::controller::setup_modules (this=0x5555559360a0, align=polybar::alignment::LEFT) at /home/amr/polybar/src/components/controller.cpp:724
        type = "internal/xworkspaces"
        ptr = 0xffffffff
        module = std::shared_ptr<polybar::modules::module_interface> (expired, weak count 0) = {get() = 0x7ffff796d410 <__cxxabiv1::__gxx_personality_v0(int, _Unwind_Action, _Unwind_Exception_Class, _Unwind_Exception*, _Unwind_Context*)>}
        module_name = "workspaces"
        __for_range = @0x7fffffffc950: std::vector of length 1, capacity 1 = {"workspaces"}
        __for_begin = "workspaces"
        __for_end = <error: Cannot access memory at address 0x73656c75646f>
        key = "modules-left"
        configured_modules = "workspaces"
#6  0x00005555555e98e9 in polybar::controller::controller (this=0x5555559360a0, conn=..., emitter=..., logger=..., config=..., bar=..., ipc=..., confwatch=...) at /home/amr/polybar/src/components/controller.cpp:92
        act = {__sigaction_handler = {sa_handler = 0x5555555e8c03 <polybar::interrupt_handler(int)>, sa_sigaction = 0x5555555e8c03 <polybar::interrupt_handler(int)>}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        created_modules = 0
        act = {__sigaction_handler = {sa_handler = <optimized out>, sa_sigaction = <optimized out>}, sa_mask = {__val = {<optimized out> <repeats 16 times>}}, sa_flags = <optimized out>, sa_restorer = <optimized out>}
        created_modules = <optimized out>
#7  0x00005555555f8868 in std::make_unique<polybar::controller, polybar::connection&, polybar::signal_emitter&, polybar::logger const&, polybar::config const&, std::unique_ptr<polybar::bar, std::default_delete<polybar::bar> >, std::unique_ptr<polybar::ipc, std::default_delete<polybar::ipc> >, std::unique_ptr<polybar::inotify_watch, std::default_delete<polybar::inotify_watch> > > () at /usr/include/c++/10.2.0/bits/unique_ptr.h:962
No locals.
#8  0x00005555555f4e5d in polybar::factory_util::unique<polybar::controller, polybar::connection&, polybar::signal_emitter&, polybar::logger const&, polybar::config const&, std::unique_ptr<polybar::bar, std::default_delete<polybar::bar> >, std::unique_ptr<polybar::ipc, std::default_delete<polybar::ipc> >, std::unique_ptr<polybar::inotify_watch, std::default_delete<polybar::inotify_watch> > > () at /home/amr/polybar/include/utils/factory.hpp:30
No locals.
#9  0x00005555555e8e6e in polybar::controller::make (ipc=..., config_watch=...) at /home/amr/polybar/src/components/controller.cpp:49
No locals.
#10 0x000055555558938e in main (argc=6, argv=0x7fffffffe108) at /home/amr/polybar/src/main.cpp:147
        xcb_screen = 0
        xcb_connection = 0x55555592dec0
        conn = @0x55555592d780: {<polybar::detail::connection_base<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>> = {<xpp::core> = {_vptr.core = 0x5555559025f0 <vtable for polybar::connection+16>, m_screen = 0, m_c = warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<xcb_connection_t*, xpp::core::core(xcb_connection_t*)::{lambda(...)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<xcb_connection_t*, xpp::core::core(xcb_connection_t*)::{lambda(...)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<xcb_connection_t> (use count 1, weak count 0) = {get() = 0x55555592dec0}}, <xpp::generic::error_dispatcher> = {_vptr.error_dispatcher = 0x5555559026d0 <vtable for polybar::connection+240>}, <polybar::detail::interfaces<polybar::detail::connection_base<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>> = {<xpp::x::interface<polybar::detail::interfaces<polybar::detail::connection_base<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>, polybar::detail::connection_base<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension> >> = {_vptr.interface = 0x5555559026e8 <vtable for polybar::connection+264>}, <xpp::randr::interface<polybar::detail::interfaces<polybar::detail::connection_base<polybar::connection&, xpp::randr::extension, xpp::composite::extension, x--Type <RET> for more, q to quit, c to continue without paging--
pp::xkb::extension>, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>, polybar::detail::connection_base<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension> >> = {_vptr.interface = 0x555555902708 <vtable for polybar::connection+296>}, <xpp::composite::interface<polybar::detail::interfaces<polybar::detail::connection_base<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>, polybar::detail::connection_base<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension> >> = {_vptr.interface = 0x555555902728 <vtable for polybar::connection+328>}, <xpp::xkb::interface<polybar::detail::interfaces<polybar::detail::connection_base<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>, polybar::detail::connection_base<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension> >> = {_vptr.interface = 0x555555902748 <vtable for polybar::connection+360>}, <No data fields>}, <xpp::x::extension> = {<No data fields>}, <xpp::x::error::dispatcher> = {<No data fields>}, <xpp::randr::extension> = {<xpp::generic::extension<xpp::randr::extension, &xcb_randr_id>> = {m_c = 0x55555592dec0, m_extension = 0x55555592d960}, <No data fields>}, <xpp::composite::extension> = {<xpp::generic::extension<xpp::composite::extension, &xcb_composite_id>> = {m_c = 0x55555592dec0, m_extension = 0x55555592d890}, <No data fields>}, <xpp::xkb::extension> = {<xpp::generic::extension<xpp::xkb::extension, &xcb_xkb_id>> = {m_c = 0x55555592dec0, m_extension = 0x55555592d8c0}, <No data fields>}, <xpp::randr::error::dispatcher> = {m_first_error = 147 '\223'}, <xpp::composite::error::dispatcher> = {m_first_error = 0 '\000'}, <xpp::xkb::error::dispatcher> = {m_first_error = 137 '\211'}, m_root_window = 1014}, m_registry = {<xpp::event::registry<polybar::connection&, xpp::randr::extension, xpp::composite::extension, xpp::xkb::extension>> = {<xpp::x::event::dispatcher<polybar::connection&>> = {m_c = @0x55555592d780}, <xpp::randr::event::dispatcher<polybar::connection&>> = {m_c = @0x55555592d780, m_first_event = 89 'Y'}, <xpp::composite::event::dispatcher<polybar::connection&>> = {m_c = @0x55555592d780, m_first_event = 0 '\000'}, <xpp::xkb::event::dispatcher<polybar::connection&>> = {m_c = @0x55555592d780, m_first_event = 85 'U'}, m_c = @0x55555592d780, m_dispatchers = std::unordered_map with 16 elements = {[22 '\026'] = std::multimap with 1 element = {[1] = 0x555555935210}, [6 '\006'] = std::multimap with 1 element = {[1] = 0x555555935210}, [8 '\b'] = std::multimap with 1 element = {[1] = 0x555555935210}, [12 '\f'] = std::multimap with 2 elements = {[1] = 0x555555935210, [3] = 0x555555933c10}, [25 '\031'] = std::multimap with 1 element = {[3] = 0x555555933c10}, [15 '\017'] = std::multimap with 1 element = {[3] = 0x555555933c10}, [28 '\034'] = std::multimap with 2 elements = {[1] = 0x555555935210, [3] = 0x555555933c10}, [7 '\a'] = std::multimap with 1 element = {[1] = 0x555555935210}, [23 '\027'] = std::multimap with 1 element = {[3] = 0x555555933c10}, [29 '\035'] = std::multimap with 1 element = {[3] = 0x555555933c10}, [21 '\025'] = std::multimap with 1 element = {[3] = 0x555555933c10}, [17 '\021'] = std::multimap with 2 elements = {[1] = 0x555555935210, [3] = 0x555555933c10}, [33 '!'] = std::multimap with 2 elements = {[1] = 0x555555935210, [3] = 0x555555933c10}, [4 '\004'] = std::multimap with 1 element = {[1] = 0x555555935210}, [19 '\023'] = std::multimap with 1 element = {[3] = 0x555555933c10}, [18 '\022'] = std::multimap with 1 element = {[3] = 0x555555933c10}}}, <No data fields>}, m_screen = 0x55555592ce94}
        confpath = "./demo-config.ini"
        parser = {m_files = std::vector of length 1, capacity 1 = {"./demo-config.ini"}, use_xrm = false, m_log = @0x55555592be30, m_config = "./demo-config.ini", m_barname = "main", m_lines = std::vector of length 5, capacity 8 = {{useful = true, file_index = 0, line_no = 1, is_header = true, header = "module/workspaces", key = "", value = ""}, {useful = true, file_index = 0, line_no = 2, is_header = false, header = "", key = "type", value = "internal/xworkspaces"}, {useful = true, file_index = 0, line_no = 4, is_header = false, header = "", key = "pin-workspaces", value = "false"}, {useful = true, file_index = 0, line_no = 6, is_header = true, header = "bar/main", key = "", value = ""}, {useful = true, file_index = 0, line_no = 7, is_header = false, header = "", key = "modules-left", value = "workspaces"}}, m_forbidden_chars = "\"'=;#[](){}:.$\\%", m_reserved_section_names = std::set with 3 elements = {[0] = "BAR", [1] = "root", [2] = "self"}}
        cli = std::unique_ptr<polybar::command_line::parser> = {get() = 0x555555929840}
        conf = @0x55555592caf0: {m_log = @0x55555592be30, m_file = "./demo-config.ini", m_barname = "main", m_sections = std::map with 2 elements = {["bar/main"] = std::unordered_map with 1 element = {["modules-left"] = "workspaces"}, ["module/workspaces"] = std::unordered_map with 2 elements = {["pin-workspaces"] = "false", ["type"] = "internal/xworkspaces"}}, m_included = std::vector of length 0, capacity 0, m_xrm = std::unique_ptr<polybar::xresource_manager> = {get() = 0x0}}
        config_watch = std::unique_ptr<polybar::inotify_watch> = {get() = 0x0}
        ctrl = std::unique_ptr<polybar::controller> = {get() = 0x0}
        scriptname = "/usr/local/bin/polybar"
        args = std::vector of length 5, capacity 5 = {"main", "-c", "./demo-config.ini", "-l", "trace"}
        xcb_error = 0
        ipc = std::unique_ptr<polybar::ipc> = {get() = 0x0}
        opts = std::vector of length 12, capacity 12 = {{flag = "-h", flag_long = "--help", desc = "Display this help and exit", token = "", values = std::vector of length 0, capacity 0}, {flag = "-v", flag_long = "--version", desc = "Display build details and exit", token = "", values = std::vector of length 0, capacity 0}, {flag = "-l", flag_long = "--log", desc = "Set the logging verbosity (default: notice)", token = "LEVEL", values = std::vector of length --Type <RET> for more, q to quit, c to continue without paging--
5, capacity 5 = {"error", "warning", "notice", "info", "trace"}}, {flag = "-q", flag_long = "--quiet", desc = "Be quiet (will override -l)", token = "", values = std::vector of length 0, capacity 0}, {flag = "-c", flag_long = "--config", desc = "Path to the configuration file", token = "FILE", values = std::vector of length 0, capacity 0}, {flag = "-r", flag_long = "--reload", desc = "Reload when the configuration has been modified", token = "", values = std::vector of length 0, capacity 0}, {flag = "-d", flag_long = "--dump", desc = "Print value of PARAM in bar section and exit", token = "PARAM", values = std::vector of length 0, capacity 0}, {flag = "-m", flag_long = "--list-monitors", desc = "Print list of available monitors and exit (Removes cloned monitors)", token = "", values = std::vector of length 0, capacity 0}, {flag = "-M", flag_long = "--list-all-monitors", desc = "Print list of all available monitors (Including cloned monitors) and exit", token = "", values = std::vector of length 0, capacity 0}, {flag = "-w", flag_long = "--print-wmname", desc = "Print the generated WM_NAME and exit", token = "", values = std::vector of length 0, capacity 0}, {flag = "-s", flag_long = "--stdout", desc = "Output data to stdout instead of drawing it to the X window", token = "", values = std::vector of length 0, capacity 0}, {flag = "-p", flag_long = "--png", desc = "Save png snapshot to FILE after running for 3 seconds", token = "FILE", values = std::vector of length 0, capacity 0}}
        exit_code = 0 '\000'
        reload = false
        logger = @0x55555592be30: {m_level = polybar::loglevel::TRACE, m_fd = 2, m_prefixes = std::map with 5 elements = {[polybar::loglevel::ERROR] = "\r\033[1;31merror: \033[0m", [polybar::loglevel::WARNING] = "\r\033[1;33mwarn: \033[0m", [polybar::loglevel::NOTICE] = "\r\033[1;34mnotice: \033[0m", [polybar::loglevel::INFO] = "\r\033[1;32m* \033[0m", [polybar::loglevel::TRACE] = "\r\033[0;32m- \033[0m"}, m_suffixes = std::map with 5 elements = {[polybar::loglevel::ERROR] = "\033[0m", [polybar::loglevel::WARNING] = "\033[0m", [polybar::loglevel::NOTICE] = "\033[0m", [polybar::loglevel::INFO] = "\033[0m", [polybar::loglevel::TRACE] = "\033[0m"}}
(gdb) 
```

**Comment by patrick96** [comment]
I think the underlying issue is a bug in i3. But nevertheless, polybar shouldn't crash because of it (the module can crash, but the bar should continue running).

What version of i3 are you using?

**Comment by amrbashir** [comment]
I am using AwesomeWM not i3

**Comment by amrbashir** [comment]
If this is an upstream issue, then I will close this issue and call it a day.
 I've already made a custom module that reads formatted text every 0.1 sec which emulates the workspaces and that's enough for me .

**Comment by patrick96** [comment]
Why did I think you were using i3? :confused: 

In that case, it's an upstream issue. I'm working on a fix that will at least not crash polybar (though the module won't work), so we can leave this open.

Just FYI, I can't reproduce this with the default awesomewm config, so maybe there is something in your config that causes this (still a bug in awesome thought that it lets you do it).

**Comment by amrbashir** [comment]
yeah you are right, I actually tested with default awesomewm config and it is working fine. I will have to dig into my awesome config to see what is wrong. Thanks for help. Should I leave this issue open ?

**Comment by patrick96** [comment]
> Should I leave this issue open ?

Yes

If you find the issue, it might be a good idea to report the bug to the awesomewm repo

**Comment by amrbashir** [comment]
I found the issue and it is not related to awesome, I had awesome start my init script and I found that I had lxsession there, removing it from init script makes polybar and the xworkspaces module work as expected. I apologize for the trouble.

**Comment by patrick96** [comment]
No worries. Segfaults should still not be possible in polybar, so I appreciate the report :)
